import React, { useState, useEffect } from 'react';
import { useNavigate, useLocation, Link } from 'react-router-dom';
import api from '../api';

export default function VerifyOtp() {
    const [otp, setOtp] = useState('');
    const [error, setError] = useState('');
    const [loading, setLoading] = useState(false);
    const [success, setSuccess] = useState('');
    const [resending, setResending] = useState(false);

    const navigate = useNavigate();
    const location = useLocation();
    const queryEmail = new URLSearchParams(location.search).get('email');
    const email = location.state?.email || queryEmail;

    useEffect(() => {
        if (!email) {
            navigate('/forgot-password');
        }
    }, [email, navigate]);

    const handleVerifySubmit = async (e) => {
        e.preventDefault();
        setError('');
        setSuccess('');
        setLoading(true);

        try {
            const response = await api.post('/api/bago/verify-otp', { email, otp });
            setSuccess('OTP verified successfully! Redirecting...');

            // The response should contain a short-lived token generated by verify-otp 
            const token = response.data?.token || response.data?.data?.token;

            setTimeout(() => {
                navigate('/reset-password', { state: { email, token } });
            }, 1000);
        } catch (err) {
            setError(err.response?.data?.message || 'Invalid or expired OTP. Please try again.');
        } finally {
            setLoading(false);
        }
    };

    const handleResend = async () => {
        setError('');
        setSuccess('');
        setResending(true);

        try {
            await api.post('/api/bago/resend-otp', { email });
            setSuccess('A new OTP has been sent to your email.');
        } catch (err) {
            setError(err.response?.data?.message || 'Failed to resend OTP.');
        } finally {
            setResending(false);
            setOtp('');
        }
    };

    if (!email) return null;

    return (
        <div className="min-h-screen bg-bg-theme flex overflow-hidden lg:flex-row flex-col">
            <div className="lg:w-1/2 w-full lg:min-h-screen h-[40vh] relative bg-[#012126] flex flex-col justify-between p-8 md:p-16 overflow-hidden">
                <div className="absolute bottom-0 right-0 w-[400px] h-[400px] bg-white/5 rounded-tl-[120px] -mr-20 -mb-20"></div>
                <div className="absolute top-20 right-20 w-48 h-48 bg-[#5845D8] rounded-full blur-[80px] opacity-40"></div>

                <div className="z-10">
                    <Link to="/">
                        <img src="/bago_logo.png" alt="Bago" className="h-8 md:h-10 brightness-0 invert opacity-90" onError={(e) => { e.target.src = '/vite.svg' }} />
                    </Link>
                </div>

                <div className="z-10 text-white mt-auto mb-10 md:mb-20">
                    <h1 className="text-4xl lg:text-6xl font-bold mb-6 leading-tight tracking-tight">Enter <br />Your OTP</h1>
                    <p className="text-base md:text-lg text-white/80 max-w-md font-medium leading-relaxed">
                        We sent a 6-digit confirmation code to {email}.
                    </p>
                </div>
            </div>

            <div className="lg:w-1/2 w-full flex items-center justify-center p-8 bg-white z-10 shadow-[-10px_0_30px_rgba(0,0,0,0.02)]">
                <div className="w-full max-w-md">
                    <h2 className="text-3xl font-bold text-[#012126] mb-2">Verify OTP</h2>
                    <p className="text-[#6B7280] font-medium mb-10">Verify your identity to reset password.</p>

                    {error && (
                        <div className="bg-red-50 border border-red-100 text-red-600 p-4 rounded-xl mb-6 text-sm font-medium">
                            {error}
                        </div>
                    )}
                    {success && (
                        <div className="bg-green-50 border border-green-100 text-green-600 p-4 rounded-xl mb-6 text-sm font-medium">
                            {success}
                        </div>
                    )}

                    <form onSubmit={handleVerifySubmit} className="space-y-6">
                        <div>
                            <label className="block text-sm font-bold text-[#012126] mb-2">6-Digit Code</label>
                            <input
                                type="text"
                                pattern="[0-9]*"
                                maxLength="6"
                                value={otp}
                                onChange={(e) => setOtp(e.target.value)}
                                className="w-full px-5 py-3.5 bg-[#f8f9fa] tracking-[1em] text-center rounded-xl border border-gray-200 focus:border-[#5845D8] focus:bg-white outline-none transition-all text-[#012126] text-xl font-bold"
                                placeholder={"000000".split('').join('')}
                                required
                            />
                        </div>

                        <button
                            type="submit"
                            disabled={loading}
                            className="w-full bg-[#5845D8] hover:bg-[#4838B5] text-white py-4 rounded-xl font-bold mt-2 transition-all shadow-md hover:shadow-lg disabled:opacity-70 disabled:hover:bg-[#5845D8]"
                        >
                            {loading ? 'Verifying...' : 'Verify Code'}
                        </button>
                    </form>

                    <p className="mt-10 text-center text-[#6B7280] font-medium">
                        Didn't receive it?{' '}
                        <button
                            type="button"
                            onClick={handleResend}
                            disabled={resending}
                            className="text-[#5845D8] font-bold hover:text-[#4838B5] transition-colors disabled:opacity-50"
                        >
                            {resending ? 'Sending...' : 'Resend Code'}
                        </button>
                    </p>
                </div>
            </div>
        </div>
    );
}
