class PhoneCountry {
  final String name;
  final String flag;
  final String dialCode;
  final String code;
  const PhoneCountry({required this.name, required this.flag, required this.dialCode, required this.code});
}

const List<PhoneCountry> allPhoneCountries = [
  PhoneCountry(name: 'Afghanistan', flag: '🇦🇫', dialCode: '+93', code: 'AF'),
  PhoneCountry(name: 'Albania', flag: '🇦🇱', dialCode: '+355', code: 'AL'),
  PhoneCountry(name: 'Algeria', flag: '🇩🇿', dialCode: '+213', code: 'DZ'),
  PhoneCountry(name: 'Andorra', flag: '🇦🇩', dialCode: '+376', code: 'AD'),
  PhoneCountry(name: 'Angola', flag: '🇦🇴', dialCode: '+244', code: 'AO'),
  PhoneCountry(name: 'Argentina', flag: '🇦🇷', dialCode: '+54', code: 'AR'),
  PhoneCountry(name: 'Armenia', flag: '🇦🇲', dialCode: '+374', code: 'AM'),
  PhoneCountry(name: 'Australia', flag: '🇦🇺', dialCode: '+61', code: 'AU'),
  PhoneCountry(name: 'Austria', flag: '🇦🇹', dialCode: '+43', code: 'AT'),
  PhoneCountry(name: 'Azerbaijan', flag: '🇦🇿', dialCode: '+994', code: 'AZ'),
  PhoneCountry(name: 'Bahamas', flag: '🇧🇸', dialCode: '+1', code: 'BS'),
  PhoneCountry(name: 'Bahrain', flag: '🇧🇭', dialCode: '+973', code: 'BH'),
  PhoneCountry(name: 'Bangladesh', flag: '🇧🇩', dialCode: '+880', code: 'BD'),
  PhoneCountry(name: 'Belarus', flag: '🇧🇾', dialCode: '+375', code: 'BY'),
  PhoneCountry(name: 'Belgium', flag: '🇧🇪', dialCode: '+32', code: 'BE'),
  PhoneCountry(name: 'Belize', flag: '🇧🇿', dialCode: '+501', code: 'BZ'),
  PhoneCountry(name: 'Benin', flag: '🇧🇯', dialCode: '+229', code: 'BJ'),
  PhoneCountry(name: 'Bhutan', flag: '🇧🇹', dialCode: '+975', code: 'BT'),
  PhoneCountry(name: 'Bolivia', flag: '🇧🇴', dialCode: '+591', code: 'BO'),
  PhoneCountry(name: 'Bosnia & Herzegovina', flag: '🇧🇦', dialCode: '+387', code: 'BA'),
  PhoneCountry(name: 'Botswana', flag: '🇧🇼', dialCode: '+267', code: 'BW'),
  PhoneCountry(name: 'Brazil', flag: '🇧🇷', dialCode: '+55', code: 'BR'),
  PhoneCountry(name: 'Brunei', flag: '🇧🇳', dialCode: '+673', code: 'BN'),
  PhoneCountry(name: 'Bulgaria', flag: '🇧🇬', dialCode: '+359', code: 'BG'),
  PhoneCountry(name: 'Burkina Faso', flag: '🇧🇫', dialCode: '+226', code: 'BF'),
  PhoneCountry(name: 'Burundi', flag: '🇧🇮', dialCode: '+257', code: 'BI'),
  PhoneCountry(name: 'Cambodia', flag: '🇰🇭', dialCode: '+855', code: 'KH'),
  PhoneCountry(name: 'Cameroon', flag: '🇨🇲', dialCode: '+237', code: 'CM'),
  PhoneCountry(name: 'Canada', flag: '🇨🇦', dialCode: '+1', code: 'CA'),
  PhoneCountry(name: 'Cape Verde', flag: '🇨🇻', dialCode: '+238', code: 'CV'),
  PhoneCountry(name: 'Central African Republic', flag: '🇨🇫', dialCode: '+236', code: 'CF'),
  PhoneCountry(name: 'Chad', flag: '🇹🇩', dialCode: '+235', code: 'TD'),
  PhoneCountry(name: 'Chile', flag: '🇨🇱', dialCode: '+56', code: 'CL'),
  PhoneCountry(name: 'China', flag: '🇨🇳', dialCode: '+86', code: 'CN'),
  PhoneCountry(name: 'Colombia', flag: '🇨🇴', dialCode: '+57', code: 'CO'),
  PhoneCountry(name: 'Comoros', flag: '🇰🇲', dialCode: '+269', code: 'KM'),
  PhoneCountry(name: 'Congo', flag: '🇨🇬', dialCode: '+242', code: 'CG'),
  PhoneCountry(name: 'Costa Rica', flag: '🇨🇷', dialCode: '+506', code: 'CR'),
  PhoneCountry(name: 'Croatia', flag: '🇭🇷', dialCode: '+385', code: 'HR'),
  PhoneCountry(name: 'Cuba', flag: '🇨🇺', dialCode: '+53', code: 'CU'),
  PhoneCountry(name: 'Cyprus', flag: '🇨🇾', dialCode: '+357', code: 'CY'),
  PhoneCountry(name: 'Czech Republic', flag: '🇨🇿', dialCode: '+420', code: 'CZ'),
  PhoneCountry(name: 'Denmark', flag: '🇩🇰', dialCode: '+45', code: 'DK'),
  PhoneCountry(name: 'Djibouti', flag: '🇩🇯', dialCode: '+253', code: 'DJ'),
  PhoneCountry(name: 'Dominican Republic', flag: '🇩🇴', dialCode: '+1', code: 'DO'),
  PhoneCountry(name: 'DR Congo', flag: '🇨🇩', dialCode: '+243', code: 'CD'),
  PhoneCountry(name: 'Ecuador', flag: '🇪🇨', dialCode: '+593', code: 'EC'),
  PhoneCountry(name: 'Egypt', flag: '🇪🇬', dialCode: '+20', code: 'EG'),
  PhoneCountry(name: 'El Salvador', flag: '🇸🇻', dialCode: '+503', code: 'SV'),
  PhoneCountry(name: 'Equatorial Guinea', flag: '🇬🇶', dialCode: '+240', code: 'GQ'),
  PhoneCountry(name: 'Eritrea', flag: '🇪🇷', dialCode: '+291', code: 'ER'),
  PhoneCountry(name: 'Estonia', flag: '🇪🇪', dialCode: '+372', code: 'EE'),
  PhoneCountry(name: 'Eswatini', flag: '🇸🇿', dialCode: '+268', code: 'SZ'),
  PhoneCountry(name: 'Ethiopia', flag: '🇪🇹', dialCode: '+251', code: 'ET'),
  PhoneCountry(name: 'Fiji', flag: '🇫🇯', dialCode: '+679', code: 'FJ'),
  PhoneCountry(name: 'Finland', flag: '🇫🇮', dialCode: '+358', code: 'FI'),
  PhoneCountry(name: 'France', flag: '🇫🇷', dialCode: '+33', code: 'FR'),
  PhoneCountry(name: 'Gabon', flag: '🇬🇦', dialCode: '+241', code: 'GA'),
  PhoneCountry(name: 'Gambia', flag: '🇬🇲', dialCode: '+220', code: 'GM'),
  PhoneCountry(name: 'Georgia', flag: '🇬🇪', dialCode: '+995', code: 'GE'),
  PhoneCountry(name: 'Germany', flag: '🇩🇪', dialCode: '+49', code: 'DE'),
  PhoneCountry(name: 'Ghana', flag: '🇬🇭', dialCode: '+233', code: 'GH'),
  PhoneCountry(name: 'Greece', flag: '🇬🇷', dialCode: '+30', code: 'GR'),
  PhoneCountry(name: 'Guatemala', flag: '🇬🇹', dialCode: '+502', code: 'GT'),
  PhoneCountry(name: 'Guinea', flag: '🇬🇳', dialCode: '+224', code: 'GN'),
  PhoneCountry(name: 'Guinea-Bissau', flag: '🇬🇼', dialCode: '+245', code: 'GW'),
  PhoneCountry(name: 'Guyana', flag: '🇬🇾', dialCode: '+592', code: 'GY'),
  PhoneCountry(name: 'Haiti', flag: '🇭🇹', dialCode: '+509', code: 'HT'),
  PhoneCountry(name: 'Honduras', flag: '🇭🇳', dialCode: '+504', code: 'HN'),
  PhoneCountry(name: 'Hungary', flag: '🇭🇺', dialCode: '+36', code: 'HU'),
  PhoneCountry(name: 'Iceland', flag: '🇮🇸', dialCode: '+354', code: 'IS'),
  PhoneCountry(name: 'India', flag: '🇮🇳', dialCode: '+91', code: 'IN'),
  PhoneCountry(name: 'Indonesia', flag: '🇮🇩', dialCode: '+62', code: 'ID'),
  PhoneCountry(name: 'Iran', flag: '🇮🇷', dialCode: '+98', code: 'IR'),
  PhoneCountry(name: 'Iraq', flag: '🇮🇶', dialCode: '+964', code: 'IQ'),
  PhoneCountry(name: 'Ireland', flag: '🇮🇪', dialCode: '+353', code: 'IE'),
  PhoneCountry(name: 'Israel', flag: '🇮🇱', dialCode: '+972', code: 'IL'),
  PhoneCountry(name: 'Italy', flag: '🇮🇹', dialCode: '+39', code: 'IT'),
  PhoneCountry(name: 'Ivory Coast', flag: '🇨🇮', dialCode: '+225', code: 'CI'),
  PhoneCountry(name: 'Jamaica', flag: '🇯🇲', dialCode: '+1', code: 'JM'),
  PhoneCountry(name: 'Japan', flag: '🇯🇵', dialCode: '+81', code: 'JP'),
  PhoneCountry(name: 'Jordan', flag: '🇯🇴', dialCode: '+962', code: 'JO'),
  PhoneCountry(name: 'Kazakhstan', flag: '🇰🇿', dialCode: '+7', code: 'KZ'),
  PhoneCountry(name: 'Kenya', flag: '🇰🇪', dialCode: '+254', code: 'KE'),
  PhoneCountry(name: 'Kosovo', flag: '🇽🇰', dialCode: '+383', code: 'XK'),
  PhoneCountry(name: 'Kuwait', flag: '🇰🇼', dialCode: '+965', code: 'KW'),
  PhoneCountry(name: 'Kyrgyzstan', flag: '🇰🇬', dialCode: '+996', code: 'KG'),
  PhoneCountry(name: 'Laos', flag: '🇱🇦', dialCode: '+856', code: 'LA'),
  PhoneCountry(name: 'Latvia', flag: '🇱🇻', dialCode: '+371', code: 'LV'),
  PhoneCountry(name: 'Lebanon', flag: '🇱🇧', dialCode: '+961', code: 'LB'),
  PhoneCountry(name: 'Lesotho', flag: '🇱🇸', dialCode: '+266', code: 'LS'),
  PhoneCountry(name: 'Liberia', flag: '🇱🇷', dialCode: '+231', code: 'LR'),
  PhoneCountry(name: 'Libya', flag: '🇱🇾', dialCode: '+218', code: 'LY'),
  PhoneCountry(name: 'Liechtenstein', flag: '🇱🇮', dialCode: '+423', code: 'LI'),
  PhoneCountry(name: 'Lithuania', flag: '🇱🇹', dialCode: '+370', code: 'LT'),
  PhoneCountry(name: 'Luxembourg', flag: '🇱🇺', dialCode: '+352', code: 'LU'),
  PhoneCountry(name: 'Madagascar', flag: '🇲🇬', dialCode: '+261', code: 'MG'),
  PhoneCountry(name: 'Malawi', flag: '🇲🇼', dialCode: '+265', code: 'MW'),
  PhoneCountry(name: 'Malaysia', flag: '🇲🇾', dialCode: '+60', code: 'MY'),
  PhoneCountry(name: 'Maldives', flag: '🇲🇻', dialCode: '+960', code: 'MV'),
  PhoneCountry(name: 'Mali', flag: '🇲🇱', dialCode: '+223', code: 'ML'),
  PhoneCountry(name: 'Malta', flag: '🇲🇹', dialCode: '+356', code: 'MT'),
  PhoneCountry(name: 'Mauritania', flag: '🇲🇷', dialCode: '+222', code: 'MR'),
  PhoneCountry(name: 'Mauritius', flag: '🇲🇺', dialCode: '+230', code: 'MU'),
  PhoneCountry(name: 'Mexico', flag: '🇲🇽', dialCode: '+52', code: 'MX'),
  PhoneCountry(name: 'Moldova', flag: '🇲🇩', dialCode: '+373', code: 'MD'),
  PhoneCountry(name: 'Monaco', flag: '🇲🇨', dialCode: '+377', code: 'MC'),
  PhoneCountry(name: 'Mongolia', flag: '🇲🇳', dialCode: '+976', code: 'MN'),
  PhoneCountry(name: 'Montenegro', flag: '🇲🇪', dialCode: '+382', code: 'ME'),
  PhoneCountry(name: 'Morocco', flag: '🇲🇦', dialCode: '+212', code: 'MA'),
  PhoneCountry(name: 'Mozambique', flag: '🇲🇿', dialCode: '+258', code: 'MZ'),
  PhoneCountry(name: 'Myanmar', flag: '🇲🇲', dialCode: '+95', code: 'MM'),
  PhoneCountry(name: 'Namibia', flag: '🇳🇦', dialCode: '+264', code: 'NA'),
  PhoneCountry(name: 'Nepal', flag: '🇳🇵', dialCode: '+977', code: 'NP'),
  PhoneCountry(name: 'Netherlands', flag: '🇳🇱', dialCode: '+31', code: 'NL'),
  PhoneCountry(name: 'New Zealand', flag: '🇳🇿', dialCode: '+64', code: 'NZ'),
  PhoneCountry(name: 'Nicaragua', flag: '🇳🇮', dialCode: '+505', code: 'NI'),
  PhoneCountry(name: 'Niger', flag: '🇳🇪', dialCode: '+227', code: 'NE'),
  PhoneCountry(name: 'Nigeria', flag: '🇳🇬', dialCode: '+234', code: 'NG'),
  PhoneCountry(name: 'North Korea', flag: '🇰🇵', dialCode: '+850', code: 'KP'),
  PhoneCountry(name: 'North Macedonia', flag: '🇲🇰', dialCode: '+389', code: 'MK'),
  PhoneCountry(name: 'Norway', flag: '🇳🇴', dialCode: '+47', code: 'NO'),
  PhoneCountry(name: 'Oman', flag: '🇴🇲', dialCode: '+968', code: 'OM'),
  PhoneCountry(name: 'Pakistan', flag: '🇵🇰', dialCode: '+92', code: 'PK'),
  PhoneCountry(name: 'Palestine', flag: '🇵🇸', dialCode: '+970', code: 'PS'),
  PhoneCountry(name: 'Panama', flag: '🇵🇦', dialCode: '+507', code: 'PA'),
  PhoneCountry(name: 'Papua New Guinea', flag: '🇵🇬', dialCode: '+675', code: 'PG'),
  PhoneCountry(name: 'Paraguay', flag: '🇵🇾', dialCode: '+595', code: 'PY'),
  PhoneCountry(name: 'Peru', flag: '🇵🇪', dialCode: '+51', code: 'PE'),
  PhoneCountry(name: 'Philippines', flag: '🇵🇭', dialCode: '+63', code: 'PH'),
  PhoneCountry(name: 'Poland', flag: '🇵🇱', dialCode: '+48', code: 'PL'),
  PhoneCountry(name: 'Portugal', flag: '🇵🇹', dialCode: '+351', code: 'PT'),
  PhoneCountry(name: 'Qatar', flag: '🇶🇦', dialCode: '+974', code: 'QA'),
  PhoneCountry(name: 'Romania', flag: '🇷🇴', dialCode: '+40', code: 'RO'),
  PhoneCountry(name: 'Russia', flag: '🇷🇺', dialCode: '+7', code: 'RU'),
  PhoneCountry(name: 'Rwanda', flag: '🇷🇼', dialCode: '+250', code: 'RW'),
  PhoneCountry(name: 'Saudi Arabia', flag: '🇸🇦', dialCode: '+966', code: 'SA'),
  PhoneCountry(name: 'Senegal', flag: '🇸🇳', dialCode: '+221', code: 'SN'),
  PhoneCountry(name: 'Serbia', flag: '🇷🇸', dialCode: '+381', code: 'RS'),
  PhoneCountry(name: 'Sierra Leone', flag: '🇸🇱', dialCode: '+232', code: 'SL'),
  PhoneCountry(name: 'Singapore', flag: '🇸🇬', dialCode: '+65', code: 'SG'),
  PhoneCountry(name: 'Slovakia', flag: '🇸🇰', dialCode: '+421', code: 'SK'),
  PhoneCountry(name: 'Slovenia', flag: '🇸🇮', dialCode: '+386', code: 'SI'),
  PhoneCountry(name: 'Somalia', flag: '🇸🇴', dialCode: '+252', code: 'SO'),
  PhoneCountry(name: 'South Africa', flag: '🇿🇦', dialCode: '+27', code: 'ZA'),
  PhoneCountry(name: 'South Korea', flag: '🇰🇷', dialCode: '+82', code: 'KR'),
  PhoneCountry(name: 'South Sudan', flag: '🇸🇸', dialCode: '+211', code: 'SS'),
  PhoneCountry(name: 'Spain', flag: '🇪🇸', dialCode: '+34', code: 'ES'),
  PhoneCountry(name: 'Sri Lanka', flag: '🇱🇰', dialCode: '+94', code: 'LK'),
  PhoneCountry(name: 'Sudan', flag: '🇸🇩', dialCode: '+249', code: 'SD'),
  PhoneCountry(name: 'Suriname', flag: '🇸🇷', dialCode: '+597', code: 'SR'),
  PhoneCountry(name: 'Sweden', flag: '🇸🇪', dialCode: '+46', code: 'SE'),
  PhoneCountry(name: 'Switzerland', flag: '🇨🇭', dialCode: '+41', code: 'CH'),
  PhoneCountry(name: 'Syria', flag: '🇸🇾', dialCode: '+963', code: 'SY'),
  PhoneCountry(name: 'Taiwan', flag: '🇹🇼', dialCode: '+886', code: 'TW'),
  PhoneCountry(name: 'Tajikistan', flag: '🇹🇯', dialCode: '+992', code: 'TJ'),
  PhoneCountry(name: 'Tanzania', flag: '🇹🇿', dialCode: '+255', code: 'TZ'),
  PhoneCountry(name: 'Thailand', flag: '🇹🇭', dialCode: '+66', code: 'TH'),
  PhoneCountry(name: 'Timor-Leste', flag: '🇹🇱', dialCode: '+670', code: 'TL'),
  PhoneCountry(name: 'Togo', flag: '🇹🇬', dialCode: '+228', code: 'TG'),
  PhoneCountry(name: 'Trinidad & Tobago', flag: '🇹🇹', dialCode: '+1', code: 'TT'),
  PhoneCountry(name: 'Tunisia', flag: '🇹🇳', dialCode: '+216', code: 'TN'),
  PhoneCountry(name: 'Turkey', flag: '🇹🇷', dialCode: '+90', code: 'TR'),
  PhoneCountry(name: 'Turkmenistan', flag: '🇹🇲', dialCode: '+993', code: 'TM'),
  PhoneCountry(name: 'Uganda', flag: '🇺🇬', dialCode: '+256', code: 'UG'),
  PhoneCountry(name: 'Ukraine', flag: '🇺🇦', dialCode: '+380', code: 'UA'),
  PhoneCountry(name: 'United Arab Emirates', flag: '🇦🇪', dialCode: '+971', code: 'AE'),
  PhoneCountry(name: 'United Kingdom', flag: '🇬🇧', dialCode: '+44', code: 'GB'),
  PhoneCountry(name: 'United States', flag: '🇺🇸', dialCode: '+1', code: 'US'),
  PhoneCountry(name: 'Uruguay', flag: '🇺🇾', dialCode: '+598', code: 'UY'),
  PhoneCountry(name: 'Uzbekistan', flag: '🇺🇿', dialCode: '+998', code: 'UZ'),
  PhoneCountry(name: 'Venezuela', flag: '🇻🇪', dialCode: '+58', code: 'VE'),
  PhoneCountry(name: 'Vietnam', flag: '🇻🇳', dialCode: '+84', code: 'VN'),
  PhoneCountry(name: 'Yemen', flag: '🇾🇪', dialCode: '+967', code: 'YE'),
  PhoneCountry(name: 'Zambia', flag: '🇿🇲', dialCode: '+260', code: 'ZM'),
  PhoneCountry(name: 'Zimbabwe', flag: '🇿🇼', dialCode: '+263', code: 'ZW'),
];
