import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

const translations = {
    en: {
        // Common
        home: 'Home',
        about: 'About Us',
        howItWorks: 'How it works',
        track: 'Track',
        login: 'Login',
        signup: 'Signup',
        dashboard: 'Dashboard',
        logout: 'Sign Out',
        back: 'Back',
        save: 'Save Changes',
        loading: 'Loading...',
        optional: 'optional',
        whoWeAre: 'Who we are',
        postTrip: 'Post a Trip',
        postNewTrip: 'Post New Trip',
        unknown: 'Unknown',
        tbd: 'TBD',

        // Home / Hero
        nextGenShipping: 'Next Generation Shipping',
        heroTitle: 'International package delivery redefined.',
        heroSummary: 'The easiest and most affordable way to send packages across the world. Connect with verified travelers ready to deliver your items.',
        deliveredStamp: 'DELIVERED',
        downloadOfficialApps: 'Download official apps',
        ratedStars: '4.9/5 RATED',
        leavingFromLabel: 'Leaving From',
        goingToLabel: 'Going To',
        pickCityPlaceHolder: 'Pick a city',
        departureDateLabel: 'Departure Date',
        searchRoutesBtn: 'Compare Global Routes',
        offerRide: 'Offer space',
        getApp: 'Get App',
        loginSignup: 'Login / Signup',
        findRoute: 'Find a Route',
        selectLanguage: 'Select Language',
        preferredCurrency: 'Preferred Currency',

        // Partners
        partners: 'Partners',
        partnershipLogistics: 'Developed in partnership with top global logistics networks.',

        // Community
        joinGlobalCommunity: 'Join our global community',
        sendWithBago: 'Send with Bago',
        travelWithBago: 'Travel with Bago',

        // Trip Types
        byFlight: 'By flight',
        byFlightDesc: 'Fly with travelers and send your packages faster.',
        byBus: 'By bus',
        byBusDesc: 'Send your packages with bus travelers.',

        // Promo
        firstDeliveryFree: 'Get Your First Delivery Free!',
        discountPromoDesc: 'Sign up today and get your first package delivered to any destination for free, or a 100% bonus on your first payout as a courier.',
        usePromoCode: 'Use Promo Code',
        validNewUsers: 'Valid for new users only.',

        // FAQ Section
        answersHeader: 'Here are Answers Related to',
        bagoService: 'Bago Service',
        joinRailsTitle: 'Join us in building the rails for global shipping.',
        getStartedBtn: 'Get started for free',
        faqQ1: 'What types of items can I send through Bago?',
        faqA1: 'You can send almost anything from documents and clothing to electronics and gifts, provided they are not on our prohibited items list and comply with international shipping laws.',
        faqQ2: 'Are my packages insured?',
        faqA2: 'Yes! Every verified shipment is backed by our secure escrow system and insurance protection policy to ensure peace of mind for both senders and travelers.',
        faqQ3: 'Who can I mail my packages to?',
        faqA3: 'You can send packages to any of the cities available on our platform. Our travelers cover thousands of routes across the globe every day.',
        faqQ4: 'How are the shipping rates determined?',
        faqA4: 'Rates are based on regional standards set by our platform and travelers, taking into account the route, package weight, and delivery speed.',

        // Features Section
        featureTitleInsurance: 'Insurance Online Payments',
        featureDescInsurance: 'With Bago your money is safe at all times. Bago uses a secure payment system and you have a guaranteed refund.',
        featureTitleGuaranteed: 'Guaranteed delivery',
        featureDescGuaranteed: 'If a traveler cancels your order or delivers an item in poor condition, we will process a full refund and try to find a new traveler for you.',
        featureTitleOptions: 'Multiple Payment Options',
        featureDescOptions: 'To make your life easier, we accept a variety of payment methods such as Visa, MasterCard and American Express, with more options available soon.',
        featureTitleNoHidden: 'No Hidden Fees',
        featureDescNoHidden: 'For total transparency, Bago uses machine learning to calculate applicable rates and taxes before you post your order. That way you will know exactly how much you are paying.',
        featureTitleCommunity: 'Community of Verified Senders and Travelers',
        featureDescCommunity: 'At Bago, trust is our highest priority, and we work hard to ensure that our community treats all its members with the utmost respect.',
        featureTitleSupport: '24/7 support',
        featureDescSupport: 'Our team of customer service professionals are at your disposal to resolve any incident that may arise during the order and delivery process.',

        // App Promotion
        scanToGetApp: 'Scan to get app',
        ourFreeAppTitle: 'Our free app.',
        appDescription: 'One app for every step of your journey—global package delivery planning has never been easier! Search routes, track shipments, and message travelers on the go.',
        mobileTrackingTitle: 'Mobile tracking',
        mobileTrackingDesc: 'Watch your package move in real-time on our map.',
        globalRoutesTitle: 'Global routes',
        globalRoutesDesc: 'Send anywhere from New York to Lagos.',
        liveUpdatesTitle: 'Live updates',
        liveUpdatesDesc: 'Get notified for every hand-off and milestone.',
        supportTitle: 'Human support',
        supportDesc: 'Chat with our 24/7 support team anytime.',

        // Tracking Section
        realTimeTrackingTitle: 'Real-time tracking. Total peace of mind.',
        realTimeTrackingDesc: 'Follow your package every step of the way. From pickup to delivery, you will know exactly where your items are and when they will arrive. Send with total confidence!',
        checkLiveStatusBtn: 'Check live status',

        // Testimonial / Car Section
        testimonialTitle: 'Only on Bago...',
        testimonialQuote: 'Perfect for me because I can send packages with courier partners! It is faster and more affordable than traditional couriers.',
        testimonialAuthor: 'Anna, Bago member since 2024',

        // Login Page
        welcomeBack: 'Welcome back',
        earnMoreSpendLess: 'Earn more. Spend less.',
        loginSubtitle: 'Log in to access your dashboard and manage your logistics.',
        signInHeader: 'Sign In',
        accessAccount: 'Access your Bago account.',
        continueWithGoogle: 'Continue with Google',
        secureAccountLogin: 'Secure Account Login',
        emailAddressLabel: 'Email address',
        passwordLabel: 'Password',
        forgotPasswordLink: 'Forgot password?',
        signInBtn: 'Sign In To Bago',
        securityCheck: 'Security Check...',
        secureLoginProtected: 'Secure login protected by Bago Encryption.',
        noAccountYet: "Don't have an account yet?",
        joinBagoToday: 'Join Bago today',

        // Signup Page
        joinOurNetwork: 'Join our network',
        moveStuffMakeMoney: 'Move stuff. Make money.',
        signupSubtitle: "The world's most human-centric logistics network is waiting for you.",
        createAccountHeader: 'Create Account',
        getStartedToday: 'Get started with Bago today.',
        checkInbox: 'Check your inbox',
        sentCodeTo: 'We sent a code to',
        verifyEmailBtn: 'Verify My Email',
        backToDetails: 'Back to details',
        quickSignup: 'Quick Signup',
        countryLabel: 'Country',
        chooseCountry: 'Choose...',
        phoneNumberLabel: 'Phone number',
        byJoiningAgree: 'By joining, you agree to our',
        shippingGuidelines: 'Shipping Guidelines',
        alreadyHaveAccount: 'Already have an account?',
        signInHere: 'Sign in here',
        passwordMinLength: 'Password must be at least 6 characters',
        validPhoneError: 'Please enter a valid phone number',
        selectCountryError: 'Please select your country',
        verificationCodeSent: 'A verification code has been sent to your email.',
        accountVerifiedRedirect: 'Account verified! Redirecting to login…',
        invalidOtpError: 'Invalid or expired OTP',
        secureAccountSignup: 'Secure Account Signup',
        confirmPasswordLabel: 'Confirm Password',
        signupBtn: 'Sign Up to Bago',
        verifyOtpBtn: 'Verify My Account',
        didntReceiveCode: "Didn't receive the code?",
        resendCode: 'Resend Code',
        agreeToTermsPrefix: 'I agree to the',
        termsAndConditions: 'Terms & Conditions',

        // Privacy Page
        privacyPolicy: 'Privacy Policy',
        gdprCompliance: 'GDPR Compliance',
        gdprDesc: 'At Bago, we are committed to protecting your privacy in accordance with the General Data Protection Regulation (GDPR) and other global privacy standards. This policy explains how we collect, use, and share your data when you use our platform.',
        informationCollect: '1. Information We Collect',
        infoCollectIntro: 'We collect information that you provide to us directly, including:',
        identityDataLabel: 'Identity Data',
        identityDataDesc: 'Name, date of birth, and government-issued ID for KYC verification.',
        contactDataLabel: 'Contact Data',
        contactDataDesc: 'Email address, phone number, and mailing address.',
        travelDataLabel: 'Travel Data',
        travelDataDesc: 'Flight details, bus tickets, origins, and destinations.',
        financialDataLabel: 'Financial Data',
        financialDataDesc: 'Bank account details and payment information (handled by secure partners).',
        useOfData: '2. Use of Data',
        useOfDataDesc: 'We use your data to facilitate peer-to-peer shipping, process payments, prevent fraud, and comply with legal obligations. Your identity data is shared with our verification partner (Didit) for the sole purpose of ensuring platform security.',
        dataRights: '3. Your Data Rights',
        dataRightsIntro: 'Under GDPR, you have the following rights regarding your personal data:',
        rightAccessTitle: 'Access',
        rightAccessDesc: 'Request a copy of your personal data.',
        rightErasureTitle: 'Erasure',
        rightErasureDesc: 'Request deletion of your account/data.',
        rightRectificationTitle: 'Rectification',
        rightRectificationDesc: 'Correct any inaccurate information.',
        rightPortabilityTitle: 'Portability',
        rightPortabilityDesc: 'Transfer your data to another service.',
        dataSecurity: '4. Data Security',
        dataSecurityDesc: 'We implement industry-standard encryption (SSL/TLS) and security protocols to protect your data. Payment information is never stored directly on our servers; it is managed by PCI-compliant payment processors.',
        exerciseRights: 'Exercise your rights?',
        contactOfficer: 'Contact Officer',

        // Terms Page
        termsConditions: 'Terms & Conditions',
        acceptanceTerms: '1. Acceptance of Terms',
        acceptanceDesc: 'By accessing or using the Bago platform ("Bago", "we", "us", or "our"), you agree to comply with and be bound by these Terms and Conditions. These terms govern your use of our website, mobile application, and related services.',
        safetyCompliance: 'Safety and compliance are our non-negotiable standards.',
        openPackageDesc1: 'Travelers have the absolute right and obligation to inspect the contents of any package they agree to transport.',
        openPackageDesc2: 'Senders MUST hand over items in an unsealed condition or open them in the presence of the traveler.',
        openPackageDesc3: 'Travelers are encouraged to take photos of the package contents during the handover as proof of condition.',
        openPackageDesc4: 'Any refusal by a sender to allow inspection is grounds for immediate cancellation of the trip and possible account suspension.',
        verificationKYC: '3. Verification (KYC)',
        verificationDesc: 'Bago uses third-party verification services to ensure the integrity of our community. Users must provide valid government-issued ID and biometric verification. We reserve the right to limit access to features until verification is complete.',
        duplicateAccounts: 'Users are permitted only one verified account. Attempting to create multiple identities or bypass security checks will result in a permanent ban.',
        protectionPolicy: '4. Protection Policy',
        protectionDesc: 'Bago provides a standard protection layer for all verified transactions completed through our platform:',
        protectionPolicy1: 'Funds are never released to a traveler until delivery is confirmed via Escrow.',
        protectionPolicy2: 'Our team will mediate cases of loss or damage via Dispute Resolution.',
        protectionPolicy3: 'Once delivery is confirmed, travelers are paid immediately to their Bago wallet.',
        prohibitions: '5. Prohibitions',
        prohibitionsDesc: 'Users are strictly prohibited from shipping illegal drugs, flammable liquids, weapons, counterfeit goods, or any items restricted by customs laws.',
        questions: 'Questions?',
        questionsHelpCenter: 'Help Center',

        // Help Center
        helpCenterTitle: 'How can we help you today?',
        helpSubtitle: 'Search our knowledge base or browse categories below',
        searchHelp: 'Search for articles...',
        shippingGuide: 'Shipping Guide',
        paymentPricing: 'Payment & Pricing',
        safetyTrust: 'Safety & Trust',
        accountSettings: 'Account Settings',
        supportTopics: 'Support Topics',
        stillNeedHelp: 'Still need help?',
        supportTeamAvailability: 'Our support team is available 24/7 to assist you with any questions or issues.',
        supportEmail: 'Support Email',
        inAppChat: 'In-app Chat',
        chatWithAssistants: 'Chat with our Bago Assistants',
        chatAssistantsDesc: 'Our AI-powered help assistants can answer most questions instantly about routes, pricing, and guidelines.',
        exploreArticles: 'EXPLORE ARTICLES',
        faqQuestion1: "What is Bago's 'Open Package Policy'?",
        faqAnswer1: "For the safety of our travelers and the platform, Bago enforces an Open Package Policy. Travelers have the absolute right to inspect the contents of any package they carry. Senders must keep items unsealed or be prepared to open them for inspection at the point of handover. This ensures no prohibited or illegal items are transported.",
        faqQuestion2: "What happens if a package is damaged or lost?",
        faqAnswer2: "Bago provides a basic 'Insurance Protection Policy' for verified transactions. If an item is lost or damage is proven to be the traveler's fault, our escrow system can facilitate refunds. We recommend travelers take photos of the item during pickup and delivery to ensure protection for both parties.",
        faqQuestion3: "How does the Escrow system work?",
        faqAnswer3: "When a sender pays for a delivery, the funds are securely held by Bago's escrow service. The traveler only receives the payment once the sender confirms receipt or the traveler provides verified proof of delivery. This protects both users from fraud.",
        faqQuestion4: "Why do I need to verify my identity?",
        faqAnswer4: "Security is our top priority. By requiring KYC (Know Your Customer) verification through Didit, we ensure that every person on the platform is who they say they are. This builds a trusted community of real travelers and real senders.",
        faqCategoryShipping: 'Shipping',
        faqCategoryPayments: 'Payments',
        faqCategorySecurity: 'Security',

        // Track Shipment
        trackShipmentTitle: 'Track Shipment',
        trackSubtitle: 'Enter your tracking number to see the real-time status of your package.',
        trackPlaceholder: 'e.g. BAGO-A1B2C3D4',
        trackNow: 'Track Now',
        shipmentNotFound: 'Shipment not found. Please check your tracking number.',
        currentStatus: 'Current Status',
        trackingNumberLabel: 'Tracking Number',
        estimatedArrival: 'Estimated Arrival',
        shipmentHistory: 'Shipment History',
        shipmentCreated: 'Shipment Created',
        bagoProtectionPolicy: 'Bago Protection Policy',
        protectionPolicyDesc: 'Every shipment on our platform is protected by Bago\'s escrow and insurance system. We guarantee safe delivery or a full refund.',
        locationLabel: 'Location',

        // Send Package
        sendPackageTitle: 'Send a Package',
        packageDetails: 'Package Details',
        itemLabel: 'What are you sending?',
        descriptionLabel: 'Detailed Description',
        itemPlaceholder: 'e.g. Laptop, Clothes, Documents',
        weightLabel: 'Package Weight (kg)',
        declarationLabel: 'Estimated Value (USD)',
        deliveryDeadlineLabel: 'Delivery Deadline',
        recipientDetails: 'Recipient Details',
        receiverNameLabel: 'Receiver Full Name',
        receiverPhoneLabel: 'Receiver Phone Number',
        shippingOptions: 'Shipping Options',
        fragileLabel: 'Fragile Item',
        perishableLabel: 'Perishable',
        refrigerationLabel: 'Requires Refrigeration',
        specialInstructionsLabel: 'Special Instructions (Optional)',
        summary: 'Summary',
        estimatedCost: 'Estimated Cost',
        from: 'From',
        to: 'To',
        serviceFee: 'Service Fee',
        totalPayable: 'Total Payable',
        requestShipping: 'Request Shipping',
        packageWeightError: 'Package weight must be between 0.1 and 50 kg',
        requestSentSuccess: 'Shipping request sent successfully!',

        // Post Trip
        postTripTitle: 'Post Your Trip',
        routeDetails: 'Route & Details',
        departureLabel: 'Departure Date',
        arrivalLabel: 'Arrival Date',
        transportMode: 'How are you traveling?',
        availableWeightLabel: 'Available Luggage Weight (kg)',
        additionalNotesLabel: 'Additional Notes',
        reviewTrip: 'Review Trip',
        confirmPost: 'Confirm & Post Trip',
        kycRequired: 'Please complete your identity verification to post a trip.',
        originDestError: 'Please select both origin and destination countries.',
        sameCityError: 'Origin and destination city cannot be the same.',
        weightRangeError: 'Available weight must be between 1 and 50 kg.',
        routeDetailsTitle: 'Route & Details',
        reviewTitle: 'Review',
        paymentTitle: 'Payment',
        doneTitle: 'Done',
        anyCity: 'Any city in',
        enterCity: 'Enter city in',
        originCountry: 'Origin Country',
        selectCountry: 'Select Country',
        originCity: 'Origin City',
        destCountry: 'Destination Country',
        destCity: 'Destination City',
        transportAndWeight: 'Transport & Weight',
        airplane: 'Airplane',
        car: 'Car',
        bus: 'Bus',
        train: 'Train',
        ship: 'Ship',
        additionalNotesPlaceholder: 'Any specific pickup/delivery preferences or item restrictions...',
        postTripHeading: 'Safe & Secure Delivery Network',
        postTripSub: 'Join our community of trusted travelers. Every trip you post helps someone send a package safely while you earn extra travel funds.',
        verifiedTransactions: 'Verified Transactions',
        escrowPayment: 'Secure Escrow Payment',
        reviewYourTrip: 'Review Your Trip',
        confirmDetails: 'Confirm your route and luggage details',
        availableWeight: 'Available Weight',
        origin: 'Origin',
        departure: 'Departure',
        destination: 'Destination',
        arrival: 'Arrival',
        tripNotes: 'Trip Notes',
        editDetails: 'Edit Details',
        tripPostedSuccess: 'Trip Submitted for Verification',
        tripPostedDesc: 'Your trip is successfully submitted. The Bago Team will verify your tickets/details. You will be notified via email once approved.',
        goDashboard: 'Go to Dashboard',

        tripActive: 'Active',
        recentRoutes: 'Recent Delivery Routes',
        nearX: 'near',
        capacityLabel: 'Capacity',
        viewDetails: 'View Details',
        // Auth flow
        forgotPasswordTitle: 'Forgot Password?',
        forgotPasswordDesc: "Don't worry, it happens to the best of us. Enter your email and we'll send you an OTP to reboot your access.",
        resetPasswordHeader: 'Reset Password',
        enterEmailLabel: 'Enter the email associated with your account.',
        sendOtpBtn: 'Send OTP',
        sendingRequest: 'Sending Request...',
        rememberedPassword: 'Remembered your password?',
        signIn: 'Sign In',
        setNewPasswordTitle: 'Set New Password!',
        setNewPasswordDesc: 'Secure your account. Almost back into the ecosystem to manage your packages and trips.',
        createPasswordHeader: 'Create Password',
        strongPasswordDesc: "Make sure it's strong and something you'll remember.",
        newPasswordLabel: 'New Password',
        updatePasswordBtn: 'Update Password',
        savingUpdate: 'Saving Update...',
        rememberOldPassword: 'Remember your old password?',
        enterOtpTitle: 'Enter Your OTP',
        sentCodeToEmailDesc: 'We sent a 6-digit confirmation code to',
        verifyOtpHeader: 'Verify OTP',
        verifyIdentityDesc: 'Verify your identity to reset password.',
        sixDigitCodeLabel: '6-Digit Code',
        verifyCodeBtn: 'Verify Code',
        verifying: 'Verifying...',
        didntReceive: "Didn't receive it?",

        // Search
        availableTravelers: 'Available Travelers',
        findTravelersDesc: 'Find travelers to deliver your package',
        selectCity: 'Select city',
        findRoutesBtn: 'Find Routes',
        filters: 'Filters',
        travelDate: 'Travel Date',
        allModes: 'All modes',
        weightKg: 'Weight (kg)',
        applyFilters: 'Apply Filters',
        noTripsFound: 'No trips found',
        tryAdjusting: 'Try adjusting your search criteria or check back later.',
        postYourTrip: 'Post Your Trip',
        spaceAvailable: 'available',
        rateStandard: 'Standard',
        sendRequestBtn: 'Send Request',
        inTransit: 'In Transit',
        outForDelivery: 'Out for Delivery',
        completed: 'Completed',

        // Original remaining keys
        heroTitleOrig: 'Global Package Delivery.',
        heroSubtitle: 'Send packages',
        heroWith: 'with courier partners.',
        leavingFrom: 'Departure Country or City',
        goingTo: 'Arrival Country or City',
        today: 'Date',
        passengers: 'Courier Partners',
        search: 'Search',
        showStays: 'Show stays',
        promoTitle: 'Earn from your travels.',
        promoDesc: 'Help others send packages as a delivery partner. Post your route and get paid for your available luggage space.',
        shareRide: 'Post a trip',
        featureTitle1: 'Send everywhere',
        featureDesc1: 'Send packages safely to any city. Our delivery partners go everywhere you need.',
        featureTitle2: 'Earn from luggage space',
        featureDesc2: 'Turn your extra luggage space into cash. A simple way to subsidize your travel costs.',
        featureTitle3: 'Trust built-in',
        featureDesc3: 'We verify every delivery partner and sender. Your package is in safe hands, every step of the way.',
        busDesc: 'Affordable way to send domestic packages',
        ratingsTitle: 'Automatic Ratings.',
        ratingsSubtitle: 'More reliable',
        ratingsSubtitle2: 'service.',
        ratingsDesc: 'We are launching Automatic Ratings to make profiles fairer and more accurate. This keeps profiles accurate so you can send with more confidence!',
        getGoing: 'Get going',

        // About Us
        aboutHero: 'Revolutionizing Logistics for Everyone.',
        aboutSubtitle: 'Bago connects travelers with people who need to send packages across the world. We\'re building a more connected, efficient, and human way to ship.',
        ourStory: 'Our Story',
        storyTitle: 'Born from a simple travel observation.',
        storyDesc1: 'The idea for Bago started when we noticed how much empty luggage space goes to waste every day across thousands of flights and bus routes. Meanwhile, sending a small parcel internationally remains prohibitively expensive and slow.',
        storyDesc2: 'We realized that travelers are the ultimate delivery network. By connecting these two groups, Bago creates a win-win: senders get faster, cheaper delivery, and travelers earn extra income to subsidize their journeys.',
        coreValues: 'Our Core Values',
        trustSafety: 'Trust & Safety',
        trustDesc: 'Every member is verified. We prioritize the security of your items and your personal data above all else.',
        globalCommunity: 'Global Community',
        globalDesc: 'We are building a borderless world where people help people, regardless of geography or distance.',
        innovation: 'Innovation',
        innovationDesc: 'Using technology to solve old problems in new ways. Constant improvement is in our DNA.',

        // Dashboard
        overview: 'Overview',
        myTrips: 'My Trips',
        myShipments: 'My Shipments',
        chats: 'Chats',
        earnings: 'Earnings',
        settings: 'Settings',
        verification: 'Verification',
        verifiedMember: 'Verified Member',
        unverifiedMember: 'Unverified Member',
        identityConfirmed: 'Identity fully confirmed.',
        underReview: 'Under Review',
        reviewDocs: 'Hang tight! Reviewing docs.',
        verifyNow: 'Verify Now',

        // Post Trip
        postTripSubtitle: 'Share your journey and earn by delivering packages',
        route: 'Route',
        fromCountry: 'From — Country',
        fromCity: 'From — City',
        toCountry: 'To — Country',
        toCity: 'To — City',
        travelDates: 'Travel Dates',
        departureDate: 'Departure Date',
        arrivalDate: 'Arrival Date',
        transportModeLabel: 'Transport Mode',
        capacity: 'Capacity',
        maxWeight: 'Maximum 50 kg per trip',
        valueUsd: 'Value (USD)',
        forInsurancePurposes: 'For insurance purposes',
        receiverInfo: 'Receiver Info',
        deliveryRoute: 'Delivery Route',
        deadlineDate: 'Deadline Date',
        attributes: 'Attributes',
        fragileSub: 'Fragile - Handle with care',
        perishableSub: 'Perishable goods',
        refrigerationSub: 'Requires refrigeration',
        findTravelers: 'Find Travelers',
        identityVerificationRequired: 'Identity Verification Required',
        verifyToSendDesc: 'You need to verify your identity before sending packages. This helps ensure the safety and trust of our community.',
        goToDashboardToVerify: 'Go to Dashboard to Verify',
        travelerInfo: 'Traveler Info',
        rate: 'Rate',
        earningsWallet: 'Earnings via Bago Wallet',
        earningsDesc: 'Earnings are credited to your Bago Wallet after delivery. Withdraw via Stripe Connect (Global) or Paystack (Africa).',
        additionalNotes: 'Additional Notes',
        notesPlaceholder: 'Any special requirements or information about your trip...',
        postingTrip: 'Posting trip...',
        tripPosted: 'Trip Posted! 🎉',
        tripSuccessDesc: 'Your trip is now live. Package senders can find and book your available space.',
        redirectDashboard: 'Redirecting to your dashboard...',

// Send Package section starts
        sendRequestTitle: 'Send Shipping Request',
        findTravelerSubtitle: 'Find a trusted traveler to deliver your package',
        requestSpaceSubtitle: 'Requesting space from',
        packageName: 'Package Name',
        packageDescription: 'Package Description',
        packageWeight: 'Package Weight (kg)',
        packageValue: 'Package Value (USD)',
        receiverName: 'Receiver Name',
        receiverPhone: 'Receiver Phone',
        deliveryDeadline: 'Delivery Deadline',
        specialInstructions: 'Special Instructions',
        fragile: 'Fragile - Handle with care',
        perishable: 'Perishable goods',
        refrigeration: 'Requires refrigeration',
        estimatedShippingCost: 'Estimated Shipping Cost',

        // How It Works
        howBagoWorks: 'How Bago Works.',
        howSubtitle: "Whether you're sending a gift to a loved one or monetizing your extra luggage space, Bago makes the process seamless, secure, and stress-free.",
        forSenders: 'For Senders',
        forTravelers: 'For Travelers',
        senderStep1Title: 'Search for a route',
        senderStep1Desc: 'Enter your departure and arrival cities, along with your preferred delivery date.',
        senderStep2Title: 'Choose your traveler',
        senderStep2Desc: 'Browse verified travelers on that route and select the one that fits your needs.',
        senderStep3Title: 'Secure payment',
        senderStep3Desc: 'Our escrow system holds your payment until the package is successfully delivered.',
        senderStep4Title: 'Track and receive',
        senderStep4Desc: 'Stay updated through real-time notifications until your package reaches its destination.',
        travelerStep1Title: 'Post your trip',
        travelerStep1Desc: 'Share your travel route (flight or bus) and indicate how much weight you can carry.',
        travelerStep2Title: 'Accept requests',
        travelerStep2Desc: 'Receive delivery requests from senders and chat with them to confirm details.',
        travelerStep3Title: 'Verified pickup',
        travelerStep3Desc: 'Meet the sender, verify the package contents, and mark the delivery as started.',
        travelerStep4Title: 'Get paid instantly',
        travelerStep4Desc: 'Once delivered, the escrow funds are released immediately to your Bago wallet.',
        prohibitedItems: 'Prohibited Items',
        prohibitedSubtitle: 'To ensure the safety of our travelers and compliance with international laws, the following items are strictly prohibited.',
        openPackagePolicy: 'Open Package Policy',
        openPackageDesc: 'Our community is built on trust. Travelers have the right to inspect package contents during pickup to ensure safety code compliance.',
        insuranceProtection: 'Insurance Protection',
        insuranceDesc: 'Every verified shipment is backed by our Insurance Protection Policy through our secure escrow system.',



        // Missing
        terms: 'Terms',
        privacy: 'Privacy',
        faqsTitle: 'FAQs',
        goToDashboard: 'Go to Dashboard',
        trustedBy: 'Trusted by 10k+ Travelers worldwide.',

        // About Us Extra
        reimagineLogistics: 'Re-imagine logistics.',
        aboutSummary: "We're building the most human-centric logistics network in the world. Bago connects travelers with people who need to send packages globally.",
        coreValuesSubtitle: 'The principles that guide every feature we build.',
        packagesSent: 'Packages Sent',
        verifiedTravelers: 'Verified Travelers',
        countriesCovered: 'Countries Covered',
        averageRating: 'Average Rating',
        joinMovement: 'Join the movement.',
        joinMovementDesc: 'Become part of the most human-centric logistics network in the world. Start sending or start earning today.',

        // How It Works Extra
        howBagoWorksTitle: 'How Bago works.',
        safetyFirst: 'Safety First',
        prohibited_IllegalSubstances: 'Illegal Substances',
        prohibited_FlammableItems: 'Flammable Items',
        prohibited_LiveAnimals: 'Live Animals',
        prohibited_PrescriptionDrugs: 'Prescription Drugs',
        prohibited_PerishableFood: 'Perishable Food',
        prohibited_LiquidLiquids: 'Liquid Liquids',
        prohibited_AerosolSprays: 'Aerosol Sprays',
        prohibited_Weaponry: 'Weaponry',
        readyToGetStarted: 'Ready to get started?',
        joinThousandsDesc: 'Join thousands of members already trusting Bago for their logistics and travel needs.',
        findRoutes: 'Find Routes',

        // Dashboard Extra
        preparingDashboard: 'Preparing your dashboard...',
        somethingWentWrong: 'Something went wrong',
        troubleLoadingSection: 'We had trouble loading this section. Please try refreshing or return to overview.',
        refreshPage: 'Refresh Page',
        backToOverview: 'Back to Overview',
        personalDashboard: 'Personal Dashboard',
        backToSite: '← Back to site',
        verified: 'Verified',
        unverified: 'Unverified',

        // Overview Extra
        fullAccessEnabled: 'Full access enabled.',
        underReviewDesc: 'Hang tight! Reviewing docs.',
        docsRejected: 'Docs were rejected.',
        tryAgain: 'Try Again',
        mismatch: 'Mismatch',
        idMismatchDesc: "ID doesn't match profile.",
        verifyAgain: 'Verify Again',
        blocked: 'Blocked',
        duplicateIdDesc: 'Duplicate ID usage.',
        completeVerificationToPost: 'Complete verification to post trips or request secure deliveries.',
        postATrip: 'Post a Trip',
        monetizeLuggageDesc: 'Monetize luggage space & earn on the go.',
        getStarted: 'Get Started',
        sendPackage: 'Send Package',
        findTravelerDesc: 'Find a traveler heading to your destination.',
        findTraveler: 'Find Traveler',
        totalEarned: 'Total Earned',
        rating: 'Rating',
        declined: 'Declined',

        // Trips Extra
        manageFlightBusRoutes: 'Manage your flight and bus routes.',
        noActiveTrips: 'No active trips',
        noActiveTripsDesc: "You haven't posted any routes yet. Start earning by sharing luggage space.",
        availableSpace: 'Available Space',
        travelMode: 'Travel Mode',
        edit: 'Edit',
        delete: 'Delete',
        spaceKg: 'Space (KG)',
        updateRoute: 'Update Route',
        deleteTripConfirm: 'Are you sure you want to delete this trip? All related shipment requests will be affected.',
        editTrip: 'Edit Trip',

        // Shipments Extra
        trackManageDeliveries: 'Track and manage your package deliveries.',
        noActiveShipments: 'No active shipments',
        noActiveShipmentsDesc: "You haven't requested any deliveries yet.",
        traveler: 'Traveler',
        dispute: 'Dispute',
        openADispute: 'Open a Dispute',
        disputeDetails: 'Dispute Details',
        disputePauseNotice: 'Raising a dispute will pause payment release to the traveler. Our team will investigate and mediate within 24-48h.',
        disputePlaceholder: 'Please describe exactly what happened (e.g. package damaged, traveler unreachable...)',
        cancelRequest: 'Cancel Request',
        submitDispute: 'Submit Dispute',
        disputeSuccessMsg: 'Dispute raised successfully. Support team will contact you.',
        failRaiseDispute: 'Failed to raise dispute',
        order: 'Order',
        packageCategory: 'Category',
        receiverInformation: 'Receiver Information',
        downloadLabel: 'Download Label',
        closeOverview: 'Close Overview',
        shipmentDetails: 'Shipment Details',
        travelerName: 'Traveler Name',
        travelerUploadedProof: 'Traveler Uploaded Proof',
        fundsInEscrow: 'Funds in Escrow',

        // Chats Extra
        activeChats: 'Active Chats',
        emptyInbox: 'Empty Inbox',
        activeNow: 'Active Now',
        encryptionActive: 'Encryption Active • Secure Link',
        securityAlert: 'Security Alert: Keep communication within Bago. Exchange of contact details is restricted to protect your payments & safety.',
        dismiss: 'Dismiss',
        typeMessage: 'Type your message...',
        selectConversation: 'Select a conversation',
        selectConversationDesc: 'Choose a chat to start messaging with travelers or senders securely.',
        openChat: 'Open chat',

        // Settings Extra
        personalInfo: 'Personal Info',
        emailSettings: 'Email Settings',
        currentEmail: 'Current Email',
        newEmailLabel: 'New Email',
        enterNewEmail: 'Enter new email',
        updateAddress: 'Update Address',
        verificationCode: 'Verification Code',
        verify: 'Verify',
        withdrawalMethods: 'Withdrawal Methods',
        stripeConnectDesc: 'Get paid directly to your bank account via Stripe. Quick setup, secure, and supports international payments.',
        accountConnected: 'Account Connected',
        readyForPayouts: 'Ready for payouts',
        connectStripe: 'Connect Stripe',
        bankTransferNgn: 'Bank Transfer (NGN)',
        bankName: 'Bank Name',
        accountNumber: 'Account Number',
        accountHolderName: 'Account Holder Name',
        saveDetails: 'Save Details',
        storedCards: 'Stored Cards',
        addCard: 'Add Card',
        enterCardDetails: 'Enter card details',
        holderName: 'Holder Name',
        cardNumber: 'Card Number',
        expMonthYear: 'MM/YY',
        cvc: 'CVC',
        noCardsStored: 'No cards stored',
        settingsUpdated: 'Settings updated successfully!',
        failedUpdateSettings: 'Failed to update settings',
        otpSentEmail: 'OTP sent to your current email',
        cardAdded: 'Card added successfully!',
        cardRemoved: 'Card removed',
        verifiedLocked: 'Verified & Locked',
        failStripeOnboarding: 'Failed to start Stripe onboarding. Please try again.',
        enterCardDetailsError: 'Please enter card number and holder name',

        // Earnings Extra
        availableBalance: 'Available Balance',
        withdraw: 'Withdraw',
        viaBankTransfer: 'Via Bank Transfer',
        viaStripeConnect: 'Via Stripe Connect',
        transferFunds: 'Transfer Funds',
        recentActivity: 'Recent Activity',
        noTransactionsRecorded: 'No transactions recorded',
        insufficientBalance: 'Insufficient balance',
        addBankDetailsFirst: 'Please add bank details in Settings first',
        addStripeDetailsFirst: 'Please add Stripe Connect ID in Settings first',
        withdrawalRequestSubmitted: 'Withdrawal request submitted!',
        withdrawalFailed: 'Withdrawal failed',
        payout: 'Payout',
        refresh: 'Refresh',
        transfer: 'Transfer',

        // Banned Page
        accountRestricted: 'Account Restricted',
        bannedMessage: 'Your account has been permanently banned for violating our community guidelines or terms of service.',
        whatCanIDo: 'What can I do?',
        appealSupport: 'If you believe this is a mistake, you can appeal this decision by contacting our support team.',
        contactSupport: 'Contact Support',
        backToHome: 'Back to Home',
        referenceId: 'Reference ID',
    },
    es: {
        // Common
        home: 'Inicio',
        about: 'Sobre Nosotros',
        howItWorks: 'Cómo funciona',
        track: 'Rastreo',
        login: 'Iniciar Sesión',
        signup: 'Registrarse',
        dashboard: 'Panel',
        logout: 'Cerrar Sesión',
        back: 'Volver',
        save: 'Guardar Cambios',
        loading: 'Cargando...',
        optional: 'opcional',
        whoWeAre: 'Quiénes somos',
        postTrip: 'Publicar Viaje',
        postNewTrip: 'Publicar Nuevo Viaje',
        unknown: 'Desconocido',
        tbd: 'Por Definir',

        // Home / Hero
        nextGenShipping: 'Envío de Próxima Generación',
        heroTitle: 'Entrega internacional de paquetes redefinida.',
        heroSummary: 'La forma más fácil y económica de enviar paquetes a todo el mundo. Conéctate con viajeros verificados listos para entregar tus artículos.',
        deliveredStamp: 'ENTREGADO',
        downloadOfficialApps: 'Descargar aplicaciones oficiales',
        ratedStars: '4.9/5 CALIFICADO',
        leavingFromLabel: 'Saliendo de',
        goingToLabel: 'Yendo a',
        pickCityPlaceHolder: 'Elige una ciudad',
        departureDateLabel: 'Fecha de salida',
        searchRoutesBtn: 'Comparar rutas globales',
        offerRide: 'Ofrecer espacio',
        getApp: 'Obtener App',
        loginSignup: 'Entrar / Registro',
        findRoute: 'Buscar Ruta',
        selectLanguage: 'Seleccionar Idioma',
        preferredCurrency: 'Moneda Preferida',

        // Partners
        partners: 'Socios',
        partnershipLogistics: 'Desarrollado en asociación con las principales redes logísticas globales.',

        // Community
        joinGlobalCommunity: 'Únete a nuestra comunidad global',
        sendWithBago: 'Enviar con Bago',
        travelWithBago: 'Viajar con Bago',

        // Trip Types
        byFlight: 'Por avión',
        byFlightDesc: 'Vuela con viajeros y envía tus paquetes más rápido.',
        byBus: 'Por autobús',
        byBusDesc: 'Envía tus paquetes con viajeros de autobús.',

        // Promo
        firstDeliveryFree: '¡Obtén tu primer envío gratis!',
        discountPromoDesc: 'Regístrate hoy y recibe tu primer paquete gratis en cualquier destino, o un bono del 100% en tu primer pago como mensajero.',
        usePromoCode: 'Usa el código promo',
        validNewUsers: 'Válido solo para nuevos usuarios.',

        // FAQ Section
        answersHeader: 'Aquí hay respuestas relacionadas con',
        bagoService: 'Servicio Bago',
        joinRailsTitle: 'Únete a nosotros para construir las bases del envío global.',
        getStartedBtn: 'Comienza gratis',
        faqQ1: '¿Qué tipo de artículos puedo enviar a través de Bago?',
        faqA1: 'Puedes enviar casi cualquier cosa, desde documentos y ropa hasta electrónica y regalos, siempre que no estén en nuestra lista de artículos prohibidos.',
        faqQ2: '¿Están asegurados mis paquetes?',
        faqA2: '¡Sí! Cada envío verificado está respaldado por nuestro sistema de depósito seguro y política de protección de seguro.',
        faqQ3: '¿A quién puedo enviar mis paquetes?',
        faqA3: 'Puedes enviar paquetes a cualquiera de las ciudades disponibles en nuestra plataforma.',
        faqQ4: '¿Cómo se determinan las tarifas de envío?',
        faqA4: 'Las tarifas se basan en estándares regionales establecidos por nuestra plataforma y viajeros.',

        // Features Section
        featureTitleInsurance: 'Pagos en línea con seguro',
        featureDescInsurance: 'Con Bago tu dinero está seguro en todo momento. Bago utiliza un sistema de pago seguro.',
        featureTitleGuaranteed: 'Entrega garantizada',
        featureDescGuaranteed: 'Si un viajero cancela o entrega en mal estado, procesamos un reembolso completo.',
        featureTitleOptions: 'Múltiples opciones de pago',
        featureDescOptions: 'Aceptamos Visa, MasterCard y American Express, con más opciones pronto.',
        featureTitleNoHidden: 'Sin cargos ocultos',
        featureDescNoHidden: 'Usamos aprendizaje automático para calcular tasas e impuestos antes de que publiques.',
        featureTitleCommunity: 'Comunidad de remitentes y viajeros verificados',
        featureDescCommunity: 'En Bago, la confianza es nuestra prioridad.',
        featureTitleSupport: 'Soporte 24/7',
        featureDescSupport: 'Nuestro equipo está a tu disposición para resolver cualquier incidente.',

        // App Promotion
        scanToGetApp: 'Escanea para obtener la app',
        ourFreeAppTitle: 'Nuestra app gratuita.',
        appDescription: 'Una aplicación para cada paso de tu viaje. ¡Planificar envíos globales nunca ha sido tan fácil!',
        mobileTrackingTitle: 'Seguimiento móvil',
        mobileTrackingDesc: 'Mira cómo se mueve tu paquete en tiempo real en nuestro mapa.',
        globalRoutesTitle: 'Rutas globales',
        globalRoutesDesc: 'Envía a cualquier lugar, desde Nueva York hasta Lagos.',
        liveUpdatesTitle: 'Actualizaciones en vivo',
        liveUpdatesDesc: 'Recibe notificaciones de cada entrega y etapa.',
        supportTitle: 'Soporte humano',
        supportDesc: 'Chatea con nuestro equipo de soporte 24/7 en cualquier momento.',

        // Tracking Section
        realTimeTrackingTitle: 'Seguimiento en tiempo real. Total tranquilidad.',
        realTimeTrackingDesc: 'Sigue tu paquete en cada paso del camino. Desde la recogida hasta la entrega, sabrás exactamente dónde están tus artículos y cuándo llegarán. ¡Envía con total confianza!',
        checkLiveStatusBtn: 'Ver estado en vivo',

        // Testimonial / Car Section
        testimonialTitle: 'Solo en Bago...',
        testimonialQuote: '¡Perfecto para mí porque puedo enviar paquetes con mensajeros socios! Es más rápido y más económico que los servicios de mensajería tradicionales.',
        testimonialAuthor: 'Anna, miembro de Bago desde 2024',

        // Login Page
        welcomeBack: 'Bienvenido de nuevo',
        earnMoreSpendLess: 'Gana más. Gasta menos.',
        loginSubtitle: 'Inicia sesión para acceder a tu panel y gestionar tu logística.',
        signInHeader: 'Iniciar Sesión',
        accessAccount: 'Acceder a tu cuenta Bago.',
        continueWithGoogle: 'Continuar con Google',
        secureAccountLogin: 'Inicio de sesión seguro',
        emailAddressLabel: 'Correo electrónico',
        passwordLabel: 'Contraseña',
        forgotPasswordLink: '¿Olvidaste tu contraseña?',
        signInBtn: 'Entrar a Bago',
        securityCheck: 'Control de seguridad...',
        secureLoginProtected: 'Inicio de sesión protegido por cifrado Bago.',
        noAccountYet: '¿Aún no tienes cuenta?',
        joinBagoToday: 'Únete a Bago hoy',

        // Signup Page
        joinOurNetwork: 'Únete a nuestra red',
        moveStuffMakeMoney: 'Mueve cosas. Gana dinero.',
        signupSubtitle: 'La red de logística más humana del mundo te espera.',
        createAccountHeader: 'Crear Cuenta',
        getStartedToday: 'Comienza con Bago hoy.',
        checkInbox: 'Revisa tu bandeja de entrada',
        sentCodeTo: 'Enviamos un código a',
        verifyEmailBtn: 'Verificar mi correo',
        backToDetails: 'Volver a detalles',
        quickSignup: 'Registro rápido',
        countryLabel: 'País',
        chooseCountry: 'Elegir...',
        phoneNumberLabel: 'Número de teléfono',
        referralOptional: 'Referido (Opcional)',
        processing: 'Procesando...',
        byJoiningAgree: 'Al unirte, aceptas nuestros',
        shippingGuidelines: 'Pautas de envío',
        alreadyHaveAccount: '¿Ya tienes una cuenta?',
        signInHere: 'Inicia sesión aquí',
        passwordMinLength: 'La contraseña debe tener al menos 6 caracteres',
        validPhoneError: 'Por favor, introduce un número de teléfono válido',
        selectCountryError: 'Por favor, selecciona tu país',
        verificationCodeSent: 'Se ha enviado un código de verificación a tu correo electrónico.',
        accountVerifiedRedirect: '¡Cuenta verificada! Redirigiendo al inicio de sesión...',
        invalidOtpError: 'OTP inválido o expirado',
        secureAccountSignup: 'Registro de cuenta seguro',
        confirmPasswordLabel: 'Confirmar contraseña',
        signupBtn: 'Registrarse en Bago',
        verifyOtpBtn: 'Verificar mi cuenta',
        didntReceiveCode: '¿No recibiste el código?',
        resendCode: 'Reenviar código',

        // Privacy Page (Spanish)
        privacyPolicy: 'Política de Privacidad',
        gdprCompliance: 'Cumplimiento GDPR',
        gdprDesc: 'En Bago, nos comprometemos a proteger su privacidad de acuerdo con el Reglamento General de Protección de Datos (GDPR) y otros estándares globales de privacidad. Esta política explica cómo recopilamos, usamos y compartimos sus datos cuando utiliza nuestra plataforma.',
        informationCollect: '1. Información que recopilamos',
        infoCollectIntro: 'Recopilamos información que usted nos proporciona directamente, incluyendo:',
        identityDataLabel: 'Datos de Identidad',
        identityDataDesc: 'Nombre, fecha de nacimiento e identificación emitida por el gobierno para la verificación KYC.',
        contactDataLabel: 'Datos de Contacto',
        contactDataDesc: 'Dirección de correo electrónico, número de teléfono y dirección postal.',
        travelDataLabel: 'Datos de Viaje',
        travelDataDesc: 'Detalles del vuelo, billetes de autobús, orígenes y destinos.',
        financialDataLabel: 'Datos Financieros',
        financialDataDesc: 'Detalles de la cuenta bancaria e información de pago (gestionada por socios seguros).',
        useOfData: '2. Uso de Datos',
        useOfDataDesc: 'Utilizamos sus datos para facilitar el envío entre pares, procesar pagos, prevenir el fraude y cumplir con las obligaciones legales. Sus datos de identidad se comparten con nuestro socio de verificación (Didit) con el único propósito de garantizar la seguridad de la plataforma.',
        dataRights: '3. Sus Derechos de Datos',
        dataRightsIntro: 'Bajo el GDPR, usted tiene los siguientes derechos con respecto a sus datos personales:',
        rightAccessTitle: 'Acceso',
        rightAccessDesc: 'Solicitar una copia de sus datos personales.',
        rightErasureTitle: 'Eliminación',
        rightErasureDesc: 'Solicitar la eliminación de su cuenta/datos.',
        rightRectificationTitle: 'Rectificación',
        rightRectificationDesc: 'Corregir cualquier información inexacta.',
        rightPortabilityTitle: 'Portabilidad',
        rightPortabilityDesc: 'Transferir sus datos a otro servicio.',
        dataSecurity: '4. Seguridad de Datos',
        dataSecurityDesc: 'Implementamos cifrado estándar de la industria (SSL/TLS) y protocolos de seguridad para proteger sus datos. La información de pago nunca se almacena directamente en nuestros servidores; es gestionada por procesadores de pago que cumplen con PCI.',
        exerciseRights: '¿Ejercer sus derechos?',
        contactOfficer: 'Contactar al Oficial',

        // Terms Page (Spanish)
        termsConditions: 'Términos y Condiciones',
        acceptanceTerms: '1. Aceptación de los Términos',
        acceptanceDesc: 'Al acceder o utilizar la plataforma Bago ("Bago", "nosotros" o "nuestro"), usted acepta cumplir y estar sujeto a estos Términos y Condiciones. Estos términos rigen su uso de nuestro sitio web, aplicación móvil y servicios relacionados.',
        safetyCompliance: 'La seguridad y el cumplimiento son nuestros estándares no negociables.',
        openPackageDesc1: 'Los viajeros tienen el derecho y la obligación absoluta de inspeccionar el contenido de cualquier paquete que acepten transportar.',
        openPackageDesc2: 'Los remitentes DEBEN entregar los artículos sin sellar o abrirlos en presencia del viajero.',
        openPackageDesc3: 'Se recomienda a los viajeros que tomen fotos del contenido del paquete durante la entrega como prueba de su estado.',
        openPackageDesc4: 'Cualquier negativa de un remitente a permitir la inspección es motivo de cancelación inmediata del viaje y posible suspensión de la cuenta.',
        verificationKYC: '3. Verificación (KYC)',
        verificationDesc: 'Bago utiliza servicios de verificación de terceros para garantizar la integridad de nuestra comunidad. Los usuarios deben proporcionar una identificación válida emitida por el gobierno y verificación biométrica. Nos reservamos el derecho de limitar el acceso a las funciones hasta que se complete la verificación.',
        duplicateAccounts: 'Los usuarios solo pueden tener una cuenta verificada. Intentar crear múltiples identidades o eludir los controles de seguridad resultará en una prohibición permanente.',
        protectionPolicy: '4. Política de Protección',
        protectionDesc: 'Bago proporciona una capa de protección estándar para todas las transacciones verificadas completadas a través de nuestra plataforma:',
        protectionPolicy1: 'Los fondos nunca se liberan a un viajero hasta que se confirma la entrega mediante Escrow.',
        protectionPolicy2: 'Nuestro equipo mediará en casos de pérdida o daño a través de la Resolución de Disputas.',
        protectionPolicy3: 'Una vez confirmada la entrega, los viajeros reciben el pago inmediatamente en su billetera Bago.',
        prohibitions: '5. Prohibiciones',
        prohibitionsDesc: 'Los usuarios tienen estrictamente prohibido enviar drogas ilegales, líquidos inflamables, armas, productos falsificados o cualquier artículo restringido por las leyes aduaneras.',
        questions: '¿Preguntas?',
        questionsHelpCenter: 'Centro de Ayuda',

        // Help Center (Spanish)
        helpCenterTitle: '¿Cómo podemos ayudarte hoy?',
        helpSubtitle: 'Busca en nuestra base de conocimientos o explore las categorías',
        searchHelp: 'Buscar artículos...',
        shippingGuide: 'Guía de Envío',
        paymentPricing: 'Pago y Precios',
        safetyTrust: 'Seguridad y Confianza',
        accountSettings: 'Configuración de la Cuenta',
        supportTopics: 'Temas de Soporte',
        stillNeedHelp: '¿Aún necesitas ayuda?',
        supportTeamAvailability: 'Nuestro equipo de soporte está disponible 24/7 para asistirte con cualquier pregunta o problema.',
        supportEmail: 'Correo de Soporte',
        inAppChat: 'Chat en la aplicación',
        chatWithAssistants: 'Chatea con nuestros asistentes de Bago',
        chatAssistantsDesc: 'Nuestros asistentes de ayuda impulsados por IA pueden responder la mayoría de las preguntas al instante sobre rutas, precios y pautas.',
        exploreArticles: 'EXPLORAR ARTÍCULOS',
        faqQuestion1: "¿Qué es la 'Política de Paquete Abierto' de Bago?",
        faqAnswer1: "Para la seguridad de nuestros viajeros y de la plataforma, Bago aplica una Política de Paquete Abierto. Los viajeros tienen el derecho absoluto de inspeccionar el contenido de cualquier paquete que transporten. Los remitentes deben mantener los artículos sin sellar o estar preparados para abrirlos para su inspección en el momento de la entrega. Esto garantiza que no se transporten artículos prohibidos o ilegales.",
        faqQuestion2: "¿Qué pasa si un paquete se daña o se pierde?",
        faqAnswer2: "Bago proporciona una 'Política de Protección de Seguro' básica para transacciones verificadas. Si un artículo se pierde o se demuestra que el daño es culpa del viajero, nuestro sistema de depósito en garantía puede facilitar los reembolsos. Recomendamos a los viajeros tomar fotos del artículo durante la recogida y la entrega para garantizar la protección de ambas partes.",
        faqQuestion3: "¿Cómo funciona el sistema de depósito en garantía (Escrow)?",
        faqAnswer3: "Cuando un remitente paga por una entrega, los fondos son retenidos de forma segura por el servicio de depósito en garantía de Bago. El viajero solo recibe el pago una vez que el remitente confirma la recepción o el viajero proporciona una prueba verificada de la entrega. Esto protege a ambos usuarios del fraude.",
        faqQuestion4: "¿Por qué necesito verificar mi identidad?",
        faqAnswer4: "La seguridad es nuestra máxima prioridad. Al requerir la verificación KYC (Conozca a su cliente) a través de Didit, nos aseguramos de que cada persona en la plataforma sea quien dice ser. Esto construye una comunidad de confianza de viajeros reales y remitentes reales.",
        faqCategoryShipping: 'Envío',
        faqCategoryPayments: 'Pagos',
        faqCategorySecurity: 'Seguridad',

        // Track Shipment (Spanish)
        trackShipmentTitle: 'Rastrear Envío',
        trackSubtitle: 'Ingrese su número de rastreo para ver el estado en tiempo real de su paquete.',
        trackPlaceholder: 'ej. BAGO-A1B2C3D4',
        trackNow: 'Rastrear Ahora',
        shipmentNotFound: 'Envío no encontrado. Por favor, verifique su número de rastreo.',
        currentStatus: 'Estado Actual',
        trackingNumberLabel: 'Número de Rastreo',
        estimatedArrival: 'Llegada Estimada',
        shipmentHistory: 'Historial de Envío',
        shipmentCreated: 'Envío Creado',
        bagoProtectionPolicy: 'Política de Protección de Bago',
        protectionPolicyDesc: 'Cada envío en nuestra plataforma está protegido por el sistema de depósito en garantía y seguro de Bago. Garantizamos una entrega segura o un reembolso completo.',
        locationLabel: 'Ubicación',

        // Send Package (Spanish)
        sendPackageTitle: 'Enviar un Paquete',
        packageDetails: 'Detalles del Paquete',
        itemLabel: '¿Qué vas a enviar?',
        descriptionLabel: 'Descripción Detallada',
        itemPlaceholder: 'ej. Portátil, Ropa, Documentos',
        weightLabel: 'Peso del Paquete (kg)',
        declarationLabel: 'Valor Estimado (USD)',
        deliveryDeadlineLabel: 'Plazo de Entrega',
        recipientDetails: 'Detalles del Destinatario',
        receiverNameLabel: 'Nombre Completo del Receptor',
        receiverPhoneLabel: 'Número de Teléfono del Receptor',
        shippingOptions: 'Opciones de Envío',
        fragileLabel: 'Artículo Frágil',
        perishableLabel: 'Perecedero',
        refrigerationLabel: 'Requiere Refrigeración',
        specialInstructionsLabel: 'Instrucciones Especiales (Opcional)',
        summary: 'Resumen',
        estimatedCost: 'Costo Estimado',
        from: 'Desde',
        to: 'A',
        serviceFee: 'Tarifa de Servicio',
        totalPayable: 'Total a Pagar',
        requestShipping: 'Solicitar Envío',
        packageWeightError: 'El peso del paquete debe estar entre 0.1 y 50 kg',
        requestSentSuccess: '¡Solicitud de envío enviada con éxito!',

        // Post Trip (Spanish)
        postTripTitle: 'Publicar tu Viaje',
        routeDetails: 'Ruta y Detalles',
        departureLabel: 'Fecha de Salida',
        arrivalLabel: 'Fecha de Llegada',
        transportMode: '¿Cómo vas a viajar?',
        availableWeightLabel: 'Peso de Equipaje Disponible (kg)',
        additionalNotesLabel: 'Notas Adicionales',
        reviewTrip: 'Revisar Viaje',
        confirmPost: 'Confirmar y Publicar Viaje',
        kycRequired: 'Por favor, complete su verificación de identidad para publicar un viaje.',
        originDestError: 'Por favor seleccione países de origen y destino.',
        sameCityError: 'La ciudad de origen y destino no pueden ser la misma.',
        weightRangeError: 'El peso disponible debe estar entre 1 y 50 kg.',
        routeDetailsTitle: 'Ruta y Detalles',
        reviewTitle: 'Revisar',
        paymentTitle: 'Pago',
        doneTitle: 'Hecho',
        anyCity: 'Cualquier ciudad en',
        enterCity: 'Ingrese ciudad en',
        originCountry: 'País de Origen',
        selectCountry: 'Seleccionar País',
        originCity: 'Ciudad de Origen',
        destCountry: 'País de Destino',
        destCity: 'Ciudad de Destino',
        transportAndWeight: 'Transporte y Peso',
        airplane: 'Avión',
        car: 'Automóvil',
        bus: 'Autobús',
        train: 'Tren',
        ship: 'Barco',
        additionalNotesPlaceholder: 'Cualquier preferencia específica de recogida/entrega o restricciones de artículos...',
        postTripHeading: 'Red de Entrega Segura y Confiable',
        postTripSub: 'Únete a nuestra comunidad de viajeros de confianza. Cada viaje que publicas ayuda a alguien a enviar un paquete de forma segura mientras ganas fondos adicionales para viajar.',
        verifiedTransactions: 'Transacciones Verificadas',
        escrowPayment: 'Pago Seguro en Escrow',
        reviewYourTrip: 'Revisa tu viaje',
        confirmDetails: 'Confirma los detalles de tu ruta y equipaje',
        availableWeight: 'Peso Disponible',
        origin: 'Origen',
        departure: 'Salida',
        destination: 'Destino',
        arrival: 'Llegada',
        tripNotes: 'Notas del Viaje',
        editDetails: 'Editar Detalles',
        tripPostedSuccess: '¡Viaje Publicado con Éxito!',
        tripPostedDesc: 'Tu viaje ya está activo. Los remitentes ahora pueden encontrar tu ruta y solicitar enviar paquetes contigo.',
        goDashboard: 'Ir al Panel de Control',

        tripActive: 'Activo',
        recentRoutes: 'Rutas de Entrega Recientes',
        nearX: 'cerca de',
        capacityLabel: 'Capacidad',
        viewDetails: 'Ver Detalles',
        // Auth flow (Spanish)
        forgotPasswordTitle: '¿Olvidaste tu contraseña?',
        forgotPasswordDesc: "No te preocupes, nos pasa a los mejores. Ingresa tu correo electrónico y te enviaremos un OTP para reiniciar tu acceso.",
        resetPasswordHeader: 'Restablecer Contraseña',
        enterEmailLabel: 'Ingresa el correo electrónico asociado con tu cuenta.',
        sendOtpBtn: 'Enviar OTP',
        sendingRequest: 'Enviando Solicitud...',
        rememberedPassword: '¿Recordaste tu contraseña?',
        signIn: 'Iniciar Sesión',
        setNewPasswordTitle: '¡Establecer Nueva Contraseña!',
        setNewPasswordDesc: 'Asegura tu cuenta. Casi de vuelta en el ecosistema para gestionar tus paquetes y viajes.',
        createPasswordHeader: 'Crear Contraseña',
        strongPasswordDesc: 'Asegúrate de que sea fuerte y algo que recuerdes.',
        newPasswordLabel: 'Nueva Contraseña',
        updatePasswordBtn: 'Actualizar Contraseña',
        savingUpdate: 'Guardando Actualización...',
        rememberOldPassword: '¿Recuerdas tu antigua contraseña?',
        enterOtpTitle: 'Ingresa tu OTP',
        sentCodeToEmailDesc: 'Enviamos un código de confirmación de 6 dígitos a',
        verifyOtpHeader: 'Verificar OTP',
        verifyIdentityDesc: 'Verifica tu identidad para restablecer la contraseña.',
        sixDigitCodeLabel: 'Código de 6 Dígitos',
        verifyCodeBtn: 'Verificar Código',
        verifying: 'Verificando...',
        didntReceive: '¿No lo recibiste?',

        // Search (Spanish)
        availableTravelers: 'Viajeros Disponibles',
        findTravelersDesc: 'Encuentra viajeros para entregar tu paquete',
        selectCity: 'Seleccionar ciudad',
        findRoutesBtn: 'Buscar Rutas',
        filters: 'Filtros',
        travelDate: 'Fecha de Viaje',
        allModes: 'Todos los modos',
        weightKg: 'Peso (kg)',
        applyFilters: 'Aplicar Filtros',
        noTripsFound: 'No se encontraron viajes',
        tryAdjusting: 'Intenta ajustar tus criterios de búsqueda o vuelve a intentarlo más tarde.',
        postYourTrip: 'Publica tu Viaje',
        spaceAvailable: 'disponible',
        rateStandard: 'Estándar',
        sendRequestBtn: 'Enviar Solicitud',
        inTransit: 'En Tránsito',
        outForDelivery: 'En Reparto',
        completed: 'Completado',

        carpool: 'Vuelo',
        heroTitleOrig: 'Entrega Global de Paquetes.',
        heroSubtitle: 'Envía paquetes',
        heroWith: 'con mensajeros socios.',
        leavingFrom: 'Ciudad o país de salida',
        goingTo: 'Ciudad o país de llegada',
        today: 'Fecha',
        passengers: 'Mensajeros socios',
        search: 'Buscar',
        showStays: 'Mostrar estancias',
        promoTitle: 'Gana con tus viajes.',
        promoDesc: 'Ayuda a otros a enviar paquetes como socio de entrega. Publica tu ruta y gana dinero por tu espacio disponible.',
        shareRide: 'Publicar un viaje',
        featureTitle1: 'Envía a todas partes',
        featureDesc1: 'Envía paquetes de forma segura a cualquier ciudad. Nuestros socios de entrega van a donde necesites.',
        featureTitle2: 'Gana por tu espacio',
        featureDesc2: 'Convierte tu espacio extra en efectivo. Una forma sencilla de subsidiar tus costos de viaje.',
        featureTitle3: 'Confianza integrada',
        featureDesc3: 'Verificamos a cada socio y remitente. Tu paquete está en buenas manos en cada paso del camino.',
        tripTypeTitle: '¿Cómo envías hoy?',
        busDescOrig: 'La forma más rápida de enviar paquetes internacionales',
        byCarpool: 'Por autobús',
        carpoolDesc: 'Forma económica de enviar paquetes nacionales',
        ratingsTitle: 'Calificaciones Automáticas.',
        ratingsSubtitle: 'Más confiable.',
        ratingsSubtitle2: 'servicio.',
        ratingsDesc: 'Lanzamos Calificaciones Automáticas para que los perfiles sean más justos y precisos. ¡Envía con más confianza!',
        getGoing: 'Comenzar',

        // About Us
        aboutHero: 'Revolucionando la Logística para Todos.',
        aboutSubtitle: 'Bago conecta viajeros con personas que necesitan enviar paquetes por todo el mundo. Estamos construyendo una forma de envío más conectada, eficiente y humana.',
        ourStory: 'Nuestra Historia',
        storyTitle: 'Nacido de una simple observación de viaje.',
        storyDesc1: 'La idea de Bago comenzó cuando notamos cuánto espacio de equipaje vacío se desperdicia cada día en miles de vuelos y rutas de autobús.',
        storyDesc2: 'Nos dimos cuenta de que los viajeros son la red de entrega definitiva. Al conectar a estos dos grupos, Bago crea una situación en la que todos ganan.',
        coreValues: 'Valores Fundamentales',
        trustSafety: 'Seguridad y Confianza',
        trustDesc: 'Cada miembro está verificado. Priorizamos la seguridad de sus artículos y sus datos personales ante todo.',
        globalCommunity: 'Comunidad Global',
        globalDesc: 'Estamos construyendo un mundo sin fronteras donde las personas ayudan a las personas, independientemente de la geografía.',
        innovation: 'Innovación',
        innovationDesc: 'Usar la tecnología para resolver viejos problemas de nuevas maneras. La mejora constante está en nuestro ADN.',

        // Dashboard
        overview: 'Resumen',
        myTrips: 'Mis Viajes',
        myShipments: 'Mis Envíos',
        chats: 'Chats',
        earnings: 'Ganancias',
        settings: 'Ajustes',
        verification: 'Verificación',
        verifiedMember: 'Miembro Verificado',
        unverifiedMember: 'No Verificado',
        identityConfirmed: 'Identidad confirmada.',
        underReview: 'En Revisión',
        reviewDocs: '¡Espera! Revisando documentos.',
        verifyNow: 'Verificar Ahora',

        // Post Trip
        route: 'Ruta',
        travelDates: 'Fechas de viaje',
        earningsWallet: 'Ganancias vía Bago Wallet',
        earningsDesc: 'Las ganancias se acreditan después de la entrega. Retira vía Stripe Connect o Paystack.',
        additionalNotes: 'Notas adicionales',
        notesPlaceholder: 'Cualquier requisito especial o información...',
        postingTrip: 'Publicando viaje...',
        tripPosted: '¡Viaje publicado! 🎉',
        tripSuccessDesc: 'Tu viaje ya está disponible para envíos.',
        redirectDashboard: 'Redirigiendo al panel...',

        // Receiver Info
        receiverInfo: 'Info del Receptor',
        receiverName: 'Nombre del destinatario',
        receiverPhone: 'Teléfono del destinatario',
        deliveryDeadline: 'Fecha límite de entrega',
        specialInstructions: 'Instrucciones especiales',
        forInsurancePurposes: 'Para fines de seguro',
        fragileSub: 'Frágil - Manejar con cuidado',
        perishableSub: 'Bienes perecederos',
        refrigerationSub: 'Requiere refrigeración',
        findTravelers: 'Buscar Viajeros',
        identityVerificationRequired: 'Verificación de Identidad Requerida',
        verifyToSendDesc: 'Debes verificar tu identidad antes de enviar paquetes. Esto garantiza la seguridad.',
        goToDashboardToVerify: 'Ir al Panel para Verificar',
        travelerInfo: 'Información del Viajero',
        rate: 'Tarifa',
        deliveryRoute: 'Ruta de Entrega',
        deadlineDate: 'Fecha Límite',
        attributes: 'Atributos',
        fragile: 'Frágil',
        perishable: 'Perecederos',
        refrigeration: 'Requiere refrigeración',

        // How It Works
        howBagoWorks: 'Cómo funciona Bago.',
        howSubtitle: 'Ya sea que envíes un regalo o monetices tu espacio extra, Bago hace que el proceso sea sencillo, seguro y sin estrés.',
        forSenders: 'Para Remitentes',
        forTravelers: 'Para Viajeros',
        senderStep1Title: 'Busca una ruta',
        senderStep1Desc: 'Ingresa tus ciudades de salida y llegada, junto con la fecha preferida.',
        senderStep2Title: 'Elige tu viajero',
        senderStep2Desc: 'Explora viajeros verificados en esa ruta y selecciona el que se ajuste a tus necesidades.',
        senderStep3Title: 'Pago seguro',
        senderStep3Desc: 'Nuestro sistema de depósito en garantía retiene tu pago hasta que el paquete se entregue.',
        senderStep4Title: 'Rastrea y recibe',
        senderStep4Desc: 'Mantente actualizado con notificaciones en tiempo real hasta el destino final.',
        travelerStep1Title: 'Publica tu viaje',
        travelerStep1Desc: 'Comparte tu ruta e indica cuánto peso puedes llevar.',
        travelerStep2Title: 'Acepta solicitudes',
        travelerStep2Desc: 'Recibe solicitudes de envío y chatea con los remitentes para confirmar detalles.',
        travelerStep3Title: 'Recogida verificada',
        travelerStep3Desc: 'Reúnete con el remitente, verifica el contenido y marca el inicio de la entrega.',
        travelerStep4Title: 'Gana al instante',
        travelerStep4Desc: 'Una vez entregado, los fondos se liberan inmediatamente a tu billetera Bago.',
        prohibitedItems: 'Artículos Prohibidos',
        prohibitedSubtitle: 'Para garantizar la seguridad y cumplir con las leyes, los siguientes artículos están prohibidos.',
        openPackagePolicy: 'Política de Paquete Abierto',
        openPackageDesc: 'Los viajeros tienen derecho a inspeccionar el contenido del paquete durante la recogida por seguridad.',
        insuranceProtection: 'Protección de Seguro',
        insuranceDesc: 'Cada envío verificado está respaldado por nuestra política de protección mediante el sistema de depósito.',

        // Missing
        terms: 'Términos',
        privacy: 'Privacidad',
        faqsTitle: 'Preguntas frecuentes',
        goToDashboard: 'Ir al Panel',
        trustedBy: 'Confiado por más de 10k viajeros en todo el mundo.',

        // Banned Page
        accountRestricted: 'Cuenta Restringida',
        bannedMessage: 'Tu cuenta ha sido suspendida permanentemente por violar nuestras guías o términos.',
        whatCanIDo: '¿Qué puedo hacer?',
        appealSupport: 'Si crees que es un error, puedes apelar contactando a soporte.',
        contactSupport: 'Contactar Soporte',
        backToHome: 'Volver a Inicio',
        referenceId: 'ID de Referencia',
        agreeToTermsPrefix: 'Acepto los',
        termsAndConditions: 'Términos y Condiciones',
    },
    fr: {
        // Common
        home: 'Accueil',
        about: 'À propos',
        howItWorks: 'Comment ça marche',
        track: 'Suivi',
        login: 'Connexion',
        signup: 'S\'inscrire',
        dashboard: 'Tableau de bord',
        logout: 'Déconnexion',
        back: 'Retour',
        save: 'Enregistrer',
        loading: 'Chargement...',
        optional: 'optionnel',
        whoWeAre: 'Qui sommes-nous',

        // Home / Hero
        nextGenShipping: 'Livraison Nouvelle Génération',
        heroTitle: 'La livraison internationale de colis redéfinie.',
        heroSummary: 'Le moyen le plus simple et le plus abordable d\'envoyer des colis dans le monde entier. Connectez-vous avec des voyageurs vérifiés.',
        deliveredStamp: 'LIVRÉ',
        downloadOfficialApps: 'Télécharger les applications officielles',
        searchRoutesBtn: 'Comparer les routes globales',

        // FAQ Section
        getStartedBtn: 'Commencer gratuitement',

        // Dashboard
        overview: 'Aperçu',
        myTrips: 'Mes Trajets',
        myShipments: 'Mes Envois',
        chats: 'Discussions',
        earnings: 'Gains',
        settings: 'Paramètres',
        verification: 'Vérification',
        verifiedMember: 'Membre Vérifié',
        verifyNow: 'Vérifier maintenant',

        // Login
        welcomeBack: 'Bon retour',
        signInHeader: 'Se connecter',
        continueWithGoogle: 'Continuer avec Google',
        signInBtn: 'Se connecter à Bago',

        // Signup
        createAccountHeader: 'Créer un compte',
        agreeToTermsPrefix: "J'accepte les",
        termsAndConditions: 'Termes et Conditions',
    },
    de: {
        // Common
        home: 'Startseite',
        about: 'Über uns',
        howItWorks: 'Wie es funktioniert',
        track: 'Verfolgen',
        login: 'Anmelden',
        signup: 'Registrieren',
        dashboard: 'Dashboard',
        logout: 'Abmelden',
        back: 'Zurück',
        save: 'Speichern',
        loading: 'Laden...',
        whoWeAre: 'Wer wir sind',

        // Home / Hero
        heroTitle: 'Weltweiter Paketversand neu definiert.',
        heroSummary: 'Der einfachste und günstigste Weg, Pakete weltweit zu versenden.',
        deliveredStamp: 'GELIEFERT',

        // Dashboard
        overview: 'Übersicht',
        myTrips: 'Meine Fahrten',
        myShipments: 'Meine Sendungen',
        chats: 'Chats',
        earnings: 'Einnahmen',
        settings: 'Einstellungen',
        verification: 'Verifizierung',
        verifiedMember: 'Verifiziertes Mitglied',
        verifyNow: 'Jetzt verifizieren',
        agreeToTermsPrefix: 'Ich stimme den',
        termsAndConditions: 'Geschäftsbedingungen zu',
    },
    pt: {
        // Common
        home: 'Início',
        about: 'Sobre Nós',
        howItWorks: 'Como funciona',
        track: 'Rastrear',
        login: 'Entrar',
        signup: 'Cadastrar',
        dashboard: 'Painel',
        logout: 'Sair',
        back: 'Voltar',
        save: 'Salvar',
        loading: 'Carregando...',
        whoWeAre: 'Quem somos',

        // Home / Hero
        heroTitle: 'Entrega global de encomendas redefinida.',
        heroSummary: 'A maneira mais fácil e acessível de enviar pacotes pelo mundo.',
        deliveredStamp: 'ENTREGUE',

        // Dashboard
        overview: 'Resumo',
        myTrips: 'Minhas Viagens',
        myShipments: 'Meus Envios',
        chats: 'Chats',
        earnings: 'Ganhos',
        settings: 'Configurações',
        verification: 'Verificação',
        verifiedMember: 'Membro Verificado',
        verifyNow: 'Verificar agora',
        agreeToTermsPrefix: 'Eu aceito os',
        termsAndConditions: 'Termos e Condições',
    }
};

const currencies = [
    { code: 'USD', name: 'US Dollar', symbol: '$', flag: '🇺🇸' },
    { code: 'EUR', name: 'Euro', symbol: '€', flag: '🇪🇺' },
    { code: 'GBP', name: 'Pound Sterling', symbol: '£', flag: '🇬🇧' },
    { code: 'CAD', name: 'Canadian Dollar', symbol: 'C$', flag: '🇨🇦' },
    { code: 'AUD', name: 'Australian Dollar', symbol: 'A$', flag: '🇦🇺' },
    { code: 'NGN', name: 'Nigerian Naira', symbol: '₦', flag: '🇳🇬' },
    { code: 'ZAR', name: 'South African Rand', symbol: 'R', flag: '🇿🇦' },
    { code: 'KES', name: 'Kenyan Shilling', symbol: 'KSh', flag: '🇰🇪' },
    { code: 'GHS', name: 'Ghanaian Cedi', symbol: '₵', flag: '🇬🇭' }
];

const languages = [
    { code: 'en', name: 'English', flag: '🇬🇧' },
    { code: 'es', name: 'Español', flag: '🇪🇸' },
    { code: 'fr', name: 'Français', flag: '🇫🇷' },
    { code: 'de', name: 'Deutsch', flag: '🇩🇪' },
    { code: 'pt', name: 'Português', flag: '🇵🇹' }
];

export function LanguageProvider({ children }) {
    const [currentLanguage, setCurrentLanguage] = useState(() => {
        return localStorage.getItem('baggo_language') || 'en';
    });

    const [currency, setCurrency] = useState(() => {
        return localStorage.getItem('baggo_currency') || 'USD';
    });

    useEffect(() => {
        localStorage.setItem('baggo_language', currentLanguage);
    }, [currentLanguage]);

    useEffect(() => {
        localStorage.setItem('baggo_currency', currency);
    }, [currency]);

    useEffect(() => {
        const checkLocationSettings = async () => {
            const hasLang = localStorage.getItem('baggo_language');
            const hasCurr = localStorage.getItem('baggo_currency');

            if (!hasLang || !hasCurr) {
                try {
                    const response = await fetch('https://ipapi.co/json/');
                    const data = await response.json();

                    if (!hasCurr && data.currency) {
                        setCurrency(data.currency);
                    }
                    if (!hasLang && data.languages) {
                        const langCode = data.languages.split(',')[0].split('-')[0].toLowerCase();
                        if (languages.find(l => l.code === langCode)) {
                            setCurrentLanguage(langCode);
                        }
                    }
                } catch (e) {
                }
            }
        };

        // If we have a user but no stored currency, check their country
        const user = JSON.parse(localStorage.getItem('user') || 'null');
        if (user && user.country && !localStorage.getItem('baggo_currency')) {
            const countryToCurrency = {
                'Nigeria': 'NGN',
                'United Kingdom': 'GBP',
                'France': 'EUR',
                'Germany': 'EUR',
                'Spain': 'EUR',
                'Italy': 'EUR',
                'Canada': 'CAD',
                'Australia': 'AUD',
                'South Africa': 'ZAR',
                'Kenya': 'KES',
                'Ghana': 'GHS'
            };
            const mapped = countryToCurrency[user.country];
            if (mapped) setCurrency(mapped);
        }

        checkLocationSettings();
    }, []);

    const t = (key) => {
        return translations[currentLanguage]?.[key] || translations.en[key] || key;
    };

    const value = {
        currentLanguage,
        setLanguage: setCurrentLanguage,
        currency,
        setCurrency,
        t,
        languages,
        currencies,
        currentLangData: languages.find(l => l.code === currentLanguage) || languages[0],
        currentCurrencyData: currencies.find(c => c.code === currency) || currencies[0]
    };

    return (
        <LanguageContext.Provider value={value}>
            {children}
        </LanguageContext.Provider>
    );
}

export function useLanguage() {
    const context = useContext(LanguageContext);
    if (!context) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
}
